// بيانات الدوائر التجارية الأولية في جدة: براندات عالمية، سينما، فنادق، تأجير سيارات.
// الإحداثيات من OpenStreetMap (Nominatim) لفروع حقيقية في جدة؛ فرعا هيرتز وسيكست في مطار الملك عبدالعزيز الدولي.
// الأسعار بالهللة. هذه الدوائر تعريفية ومتاجرها تجريبية عبر محفظة ناس لايف، وليست مرتبطة رسمياً بالعلامات.
const P = (sar) => Math.round(sar * 100);
const product = (id, title, sar, description = "", extra = {}) => ({ id, kind: "product", title, description, price: P(sar), unit: "item", stock: 50, ...extra });
const movie = (id, title, sar, meta) => ({ id, kind: "showtime", title, description: `${meta.genre} · ${meta.minutes} دقيقة · ${meta.rating}`, price: P(sar), unit: "ticket", stock: meta.seats ?? 120, meta });
const room = (id, title, sar, stock, meta) => ({ id, kind: "room", title, description: `${meta.beds} · حتى ${meta.guests} أشخاص · ${meta.size} م²${meta.breakfast ? " · شامل الإفطار" : ""}`, price: P(sar), unit: "night", stock, meta });
// عيادة بمواعيد (مجانية افتراضياً): times أوقات اليوم، days أيام العمل (0=الأحد … 6=السبت)، capacity مرضى لكل موعد
const clinic = (id, title, description, meta, sar = 0) => ({ id, kind: "clinic", title, description, price: P(sar), unit: "visit", stock: meta.capacity ?? 4, meta: { minutes: 20, days: [0, 1, 2, 3, 4], ...meta } });
// خدمة أو قسم تعريفي (لا يُطلب): الموقع وساعات العمل والإرشادات
const info = (id, title, description, meta = {}) => ({ id, kind: "info", title, description, price: 0, unit: "item", stock: null, meta });
const car = (id, title, sar, stock, meta) => ({ id, kind: "car", title, description: `${meta.cls} · ${meta.seats} مقاعد · ${meta.transmission} · ${meta.year}`, price: P(sar), unit: "day", stock, meta });

export const SEED = [
  // ---------------------------------------------------------------- براندات عالمية
  { id: "biz-ikea", name: "IKEA", nameAr: "إيكيا", category: "brand", sector: "أثاث ومفروشات", color: "#0058A3",
    description: "أثاث ومستلزمات منزلية بتصميم سويدي وأسعار في المتناول. معرض جدة على شارع التحلية.",
    lat: 21.5572307, lng: 39.1831523, address: "شارع الأمير محمد بن عبدالعزيز (التحلية)، العزيزية، جدة", hours: "يومياً 9:00 ص – 12:00 م", website: "https://www.ikea.com/sa/ar/",
    highlights: ["توصيل وتركيب", "استرجاع خلال 365 يوماً", "مطعم إيكيا"],
    items: [product("ikea-billy", "مكتبة BILLY", 449, "مكتبة خشبية 80×28×202 سم، لون أبيض"), product("ikea-lack", "طاولة جانبية LACK", 79, "55×55 سم"), product("ikea-poang", "كرسي بذراعين POÄNG", 549, "هيكل قشرة بتولا مع وسادة"), product("ikea-lamp", "مصباح مكتب FORSÅ", 129), product("ikea-duvet", "غطاء لحاف وكيسا وسادة", 199, "قطن 240×220 سم", { meta: { oldPrice: P(249) } })] },
  { id: "biz-starbucks", name: "Starbucks", nameAr: "ستاربكس", category: "brand", sector: "مقهى", color: "#00704A",
    description: "قهوة مختصة ومشروبات موسمية ومخبوزات. فرع التحلية مفتوح حتى وقت متأخر.",
    lat: 21.5582319, lng: 39.1851767, address: "شارع الأمير محمد بن عبدالعزيز (التحلية)، العزيزية، جدة", hours: "يومياً 6:00 ص – 2:00 ص", website: "https://www.starbucks.sa",
    highlights: ["طلب واستلام", "واي فاي مجاني", "جلسات خارجية"],
    items: [product("sb-caramel", "كراميل ماكياتو", 24, "حجم كبير"), product("sb-latte", "كافيه لاتيه", 19), product("sb-frap", "فرابتشينو موكا", 27), product("sb-croissant", "كرواسون زبدة", 14), product("sb-beans", "حبوب قهوة Pike Place 250غ", 55)] },
  { id: "biz-mcdonalds", name: "McDonald's", nameAr: "ماكدونالدز", category: "brand", sector: "وجبات سريعة", color: "#DA291C",
    description: "وجبات سريعة على كورنيش جدة مع خدمة السيارات على مدار الساعة.",
    lat: 21.5163427, lng: 39.154406, address: "طريق الكورنيش، الحمراء، جدة", hours: "24 ساعة", website: "https://www.mcdonalds.com.sa",
    highlights: ["خدمة السيارات", "توصيل", "منطقة ألعاب للأطفال"],
    items: [product("mc-bigmac", "وجبة بيج ماك", 31), product("mc-chicken", "وجبة ماك تشيكن", 27), product("mc-nuggets", "ناغتس 9 قطع", 18), product("mc-fries", "بطاطس كبير", 12), product("mc-mcflurry", "ماك فلوري أوريو", 12)] },
  { id: "biz-nike", name: "Nike", nameAr: "نايكي", category: "brand", sector: "ملابس وأحذية رياضية", color: "#111111",
    description: "أحذية وملابس رياضية للجري والتدريب وكرة القدم.",
    lat: 21.5832099, lng: 39.1409169, address: "شارع عبدالله جاسر، الزهراء، جدة", hours: "يومياً 10:00 ص – 12:00 م", website: "https://www.nike.sa",
    highlights: ["استبدال خلال 30 يوماً", "قياس القدم بالمتجر"],
    items: [product("nike-af1", "Nike Air Force 1", 499, "أبيض، مقاسات 40–46"), product("nike-am90", "Nike Air Max 90", 649), product("nike-tee", "تيشيرت Dri-FIT", 129), product("nike-short", "شورت تدريب", 149), product("nike-bag", "حقيبة رياضية Brasilia", 179, "", { meta: { oldPrice: P(219) } })] },
  { id: "biz-zara", name: "Zara", nameAr: "زارا", category: "brand", sector: "أزياء", color: "#1F1F1F",
    description: "أزياء رجالية ونسائية وأطفال بتشكيلات موسمية متجددة.",
    lat: 21.5829887, lng: 39.1404732, address: "شارع عبدالله جاسر، الزهراء، جدة", hours: "يومياً 10:00 ص – 12:00 م", website: "https://www.zara.com/sa/ar/",
    highlights: ["تشكيلة جديدة أسبوعياً", "استرجاع خلال 30 يوماً"],
    items: [product("zara-shirt", "قميص قطن أوكسفورد", 149), product("zara-jeans", "بنطال جينز مستقيم", 199), product("zara-dress", "فستان ميدي", 259), product("zara-jacket", "جاكيت بومبر", 359), product("zara-shoes", "حذاء جلد", 229)] },
  { id: "biz-adidas", name: "adidas", nameAr: "أديداس", category: "brand", sector: "ملابس وأحذية رياضية", color: "#000000",
    description: "أحذية وملابس رياضية ومنتجات الأصالة (Originals).",
    lat: 21.5831817, lng: 39.1398881, address: "شارع عبدالله جاسر، الزهراء، جدة", hours: "يومياً 10:00 ص – 12:00 م", website: "https://www.adidas.sa",
    highlights: ["عضوية adiClub", "استبدال مجاني"],
    items: [product("adi-samba", "adidas Samba OG", 449), product("adi-ultra", "Ultraboost 5", 799), product("adi-track", "تراك سوت Firebird", 349), product("adi-socks", "جوارب رياضية 3 أزواج", 59), product("adi-ball", "كرة قدم Al Rihla", 129)] },
  { id: "biz-samsung", name: "Samsung", nameAr: "سامسونج", category: "brand", sector: "إلكترونيات", color: "#1428A0",
    description: "هواتف وأجهزة لوحية وساعات وشاشات مع خدمة ما بعد البيع.",
    lat: 21.5124576, lng: 39.1730503, address: "شارع حائل، الرويس، جدة", hours: "السبت – الخميس 10:00 ص – 11:00 م", website: "https://www.samsung.com/sa/",
    highlights: ["تقسيط بدون فوائد", "صيانة معتمدة", "استبدال الجهاز القديم"],
    items: [product("ss-s24", "Galaxy S24 256GB", 3499), product("ss-a55", "Galaxy A55", 1499), product("ss-watch7", "Galaxy Watch7", 1099), product("ss-buds3", "Galaxy Buds3", 499, "", { meta: { oldPrice: P(599) } }), product("ss-tv55", "شاشة Crystal UHD 55 بوصة", 1899)] },
  { id: "biz-carrefour", name: "Carrefour", nameAr: "كارفور", category: "brand", sector: "هايبر ماركت", color: "#004E9F",
    description: "هايبر ماركت متكامل: مواد غذائية طازجة وأجهزة ومستلزمات منزلية.",
    lat: 21.5726649, lng: 39.1303466, address: "طريق صاري، الزهراء، جدة", hours: "يومياً 8:00 ص – 1:00 ص", website: "https://www.carrefourksa.com",
    highlights: ["توصيل خلال ساعة", "نقاط MyCLUB"],
    items: [product("cf-basket", "سلة خضار وفواكه أسبوعية", 79), product("cf-rice", "أرز بسمتي 10 كجم", 69), product("cf-oil", "زيت زيتون بكر 1 لتر", 45), product("cf-water", "ماء 40 عبوة", 19), product("cf-clean", "حزمة منظفات منزلية", 59)] },
  { id: "biz-sephora", name: "Sephora", nameAr: "سيفورا", category: "brand", sector: "تجميل وعطور", color: "#000000",
    description: "عطور ومستحضرات تجميل وعناية بالبشرة من أشهر العلامات.",
    lat: 21.5566011, lng: 39.18553, address: "شارع الأمير محمد بن عبدالعزيز (التحلية)، العزيزية، جدة", hours: "يومياً 10:00 ص – 12:00 م", website: "https://www.sephora.sa",
    highlights: ["تجربة المنتجات بالمتجر", "هدايا مع الطلبات"],
    items: [product("sp-libre", "عطر YSL Libre 50 مل", 449), product("sp-found", "كريم أساس Fenty", 189), product("sp-mascara", "ماسكارا Too Faced", 129), product("sp-lip", "أحمر شفاه MAC", 99), product("sp-palette", "بالِت ظلال Huda Beauty", 259)] },
  { id: "biz-lego", name: "LEGO", nameAr: "ليغو", category: "brand", sector: "ألعاب", color: "#FFCF00",
    description: "متجر ليغو المعتمد في مول العرب: مجموعات لكل الأعمار وجدار المكعبات.",
    lat: 21.6328847, lng: 39.1571856, address: "مول العرب، شارع النزهة، جدة", hours: "يومياً 10:00 ص – 12:00 م", website: "https://www.lego.com/ar-sa",
    highlights: ["جدار Pick a Brick", "تغليف هدايا"],
    items: [product("lego-city", "LEGO City محطة الإطفاء", 349), product("lego-technic", "LEGO Technic سيارة سباق", 599), product("lego-classic", "LEGO Classic صندوق مكعبات كبير", 149), product("lego-sw", "LEGO Star Wars سفينة الألفية", 899, "", { meta: { oldPrice: P(999) } })] },

  // ---------------------------------------------------------------- سينما
  { id: "biz-vox", name: "VOX Cinemas", nameAr: "فوكس سينما", category: "cinema", sector: "سينما", color: "#E4002B",
    description: "صالات عرض حديثة مع MAX وGOLD وتجربة عائلية. فرع التحلية.",
    lat: 21.5561234, lng: 39.1839002, address: "شارع الأمير محمد بن عبدالعزيز (التحلية)، العزيزية، جدة", hours: "يومياً 1:00 م – 2:00 ص", website: "https://ksa.voxcinemas.com",
    highlights: ["صالة GOLD", "شاشة MAX", "مقاعد مريحة"],
    items: [movie("vox-mission", "المهمة المستحيلة: الحساب الأخير", 65, { genre: "أكشن", minutes: 163, rating: "PG15", hall: "MAX", times: ["16:00", "19:30", "23:00"], seats: 140 }),
      movie("vox-insideout", "قلباً وقالباً 2", 55, { genre: "عائلي", minutes: 96, rating: "G", hall: "صالة 4", times: ["14:00", "17:00"], seats: 110 }),
      movie("vox-gladiator", "Gladiator II", 65, { genre: "دراما تاريخية", minutes: 148, rating: "PG15", hall: "صالة 2", times: ["20:00", "23:30"], seats: 120 })] },
  { id: "biz-muvi", name: "muvi Cinemas", nameAr: "موڤي سينما", category: "cinema", sector: "سينما", color: "#6D28D9",
    description: "سلسلة السينما السعودية في الرويس بصالات Xperience وSuite.",
    lat: 21.5275894, lng: 39.1789967, address: "شارع قادة الفكر، الرويس، جدة", hours: "يومياً 12:00 م – 2:00 ص", website: "https://www.muvicinemas.com",
    highlights: ["صالة Suite", "Xperience", "أفلام عربية"],
    items: [movie("muvi-dune", "Dune: Part Two", 60, { genre: "خيال علمي", minutes: 166, rating: "PG15", hall: "Xperience", times: ["15:30", "19:00", "22:30"], seats: 150 }),
      movie("muvi-hobal", "هوبال", 50, { genre: "دراما سعودية", minutes: 118, rating: "PG12", hall: "صالة 6", times: ["17:30", "21:00"], seats: 100 }),
      movie("muvi-moana", "Moana 2", 55, { genre: "رسوم متحركة", minutes: 100, rating: "G", hall: "صالة 1", times: ["13:00", "16:00"], seats: 120 })] },
  { id: "biz-amc", name: "AMC Cinemas", nameAr: "إيه إم سي سينما", category: "cinema", sector: "سينما", color: "#C8102E",
    description: "AMC على طريق صاري بصالات IMAX ومقاعد قابلة للاستلقاء.",
    lat: 21.572826, lng: 39.1274676, address: "طريق صاري، الزهراء، جدة", hours: "يومياً 1:00 م – 1:30 ص", website: "https://www.amccinemas.com",
    highlights: ["IMAX", "مقاعد Recliner", "Dolby Atmos"],
    items: [movie("amc-oppen", "Oppenheimer", 70, { genre: "سيرة ذاتية", minutes: 180, rating: "PG15", hall: "IMAX", times: ["18:00", "22:00"], seats: 200 }),
      movie("amc-deadpool", "Deadpool & Wolverine", 65, { genre: "أكشن كوميدي", minutes: 128, rating: "R15", hall: "صالة 3", times: ["16:30", "19:30", "23:00"], seats: 120 }),
      movie("amc-garfield", "The Garfield Movie", 50, { genre: "رسوم متحركة", minutes: 101, rating: "G", hall: "صالة 5", times: ["14:00", "17:00"], seats: 110 })] },

  // ---------------------------------------------------------------- فنادق
  { id: "biz-hilton", name: "Jeddah Hilton", nameAr: "هيلتون جدة", category: "hotel", sector: "فندق 5 نجوم", color: "#0B2D5B",
    description: "فندق خمس نجوم على كورنيش جدة الشمالي بإطلالة على البحر الأحمر ومسابح ومطاعم متعددة.",
    lat: 21.6047904, lng: 39.1088936, address: "طريق الكورنيش، الشاطئ، جدة", hours: "الاستقبال 24 ساعة", website: "https://www.hilton.com", phone: "+966126590000",
    highlights: ["إطلالة بحرية", "مسبح خارجي", "نادي صحي", "مواقف مجانية"],
    items: [room("hil-deluxe", "غرفة ديلوكس", 650, 20, { beds: "سرير كينغ", guests: 2, size: 36, breakfast: true, view: "المدينة" }), room("hil-sea", "غرفة عائلية بإطلالة بحرية", 950, 10, { beds: "سريران كوين", guests: 4, size: 48, breakfast: true, view: "البحر" }), room("hil-suite", "جناح تنفيذي", 1200, 8, { beds: "سرير كينغ + صالة", guests: 3, size: 70, breakfast: true, view: "البحر" })] },
  { id: "biz-parkhyatt", name: "Park Hyatt Jeddah", nameAr: "بارك حياة جدة", category: "hotel", sector: "فندق 5 نجوم", color: "#3A2E2A",
    description: "فندق فاخر بجوار مرسى اليخوت على الكورنيش، بحدائق وسبا وإطلالة على نافورة الملك فهد.",
    lat: 21.5136948, lng: 39.1546991, address: "طريق الكورنيش، الحمراء، جدة", hours: "الاستقبال 24 ساعة", website: "https://www.hyatt.com", phone: "+966122639666",
    highlights: ["مرسى يخوت", "سبا", "شاطئ خاص"],
    items: [room("ph-park", "غرفة بارك", 1400, 15, { beds: "سرير كينغ", guests: 2, size: 45, breakfast: true, view: "الحديقة" }), room("ph-sea", "غرفة بإطلالة على البحر", 1900, 10, { beds: "سرير كينغ", guests: 2, size: 45, breakfast: true, view: "البحر" }), room("ph-suite", "جناح بارك", 2600, 5, { beds: "سرير كينغ + صالة", guests: 3, size: 90, breakfast: true, view: "البحر" })] },
  { id: "biz-rosewood", name: "Rosewood Jeddah", nameAr: "روزوود جدة", category: "hotel", sector: "فندق 5 نجوم", color: "#6B4F3A",
    description: "فندق فاخر على الكورنيش الشمالي بتصميم عصري ومطاعم راقية.",
    lat: 21.5765069, lng: 39.1103106, address: "طريق الكورنيش الشمالي، الشاطئ، جدة", hours: "الاستقبال 24 ساعة", website: "https://www.rosewoodhotels.com", phone: "+966122607777",
    highlights: ["إطلالة بحرية", "مطاعم عالمية", "خدمة الخادم الشخصي"],
    items: [room("rw-premier", "غرفة بريميير", 1500, 12, { beds: "سرير كينغ", guests: 2, size: 50, breakfast: true, view: "البحر" }), room("rw-suite", "جناح روزوود", 2900, 4, { beds: "سرير كينغ + صالة", guests: 3, size: 110, breakfast: true, view: "البحر" })] },
  { id: "biz-sheraton", name: "Sheraton Jeddah", nameAr: "شيراتون جدة", category: "hotel", sector: "فندق 5 نجوم", color: "#5B2A86",
    description: "فندق على كورنيش جدة بغرف واسعة ومسبح وقاعات اجتماعات.",
    lat: 21.614279, lng: 39.1085945, address: "طريق الكورنيش، الشاطئ، جدة", hours: "الاستقبال 24 ساعة", website: "https://www.marriott.com", phone: "+966126992212",
    highlights: ["مسبح", "قاعات مناسبات", "قريب من الكورنيش"],
    items: [room("sh-classic", "غرفة كلاسيك", 520, 25, { beds: "سرير كينغ", guests: 2, size: 34, breakfast: false, view: "المدينة" }), room("sh-club", "غرفة كلوب بإطلالة بحرية", 890, 10, { beds: "سرير كينغ", guests: 2, size: 40, breakfast: true, view: "البحر" })] },
  { id: "biz-novotel", name: "Novotel Jeddah Tahlia", nameAr: "نوفوتيل جدة التحلية", category: "hotel", sector: "فندق 4 نجوم", color: "#1E4E9C",
    description: "فندق عصري في قلب شارع التحلية قريب من المطاعم والتسوق.",
    lat: 21.5551244, lng: 39.1721735, address: "شارع الأمير محمد بن عبدالعزيز (التحلية)، الأندلس، جدة", hours: "الاستقبال 24 ساعة", website: "https://all.accor.com", phone: "+966126062222",
    highlights: ["موقع مركزي", "إفطار مفتوح", "نادي رياضي"],
    items: [room("nv-standard", "غرفة قياسية", 420, 30, { beds: "سرير كوين", guests: 2, size: 28, breakfast: true, view: "المدينة" }), room("nv-exec", "غرفة تنفيذية", 690, 10, { beds: "سرير كينغ", guests: 2, size: 34, breakfast: true, view: "المدينة" })] },

  // ---------------------------------------------------------------- تأجير سيارات
  { id: "biz-budget", name: "Budget", nameAr: "بدجت لتأجير السيارات", category: "car_rental", sector: "تأجير سيارات", color: "#ED5C0F",
    description: "تأجير يومي وشهري بأسطول حديث مع توصيل السيارة إلى موقعك.",
    lat: 21.5637872, lng: 39.1671308, address: "شارع حمد الحقيل، الروضة، جدة", hours: "السبت – الخميس 8:00 ص – 10:00 م", website: "https://www.budgetsaudi.com", phone: "+966920000004",
    highlights: ["توصيل السيارة", "كيلومترات مفتوحة", "تأمين شامل اختياري"],
    items: [car("bg-yaris", "تويوتا يارس 2024", 95, 6, { cls: "اقتصادية", seats: 5, transmission: "أوتوماتيك", year: 2024, fuel: "بنزين" }), car("bg-elantra", "هيونداي إلنترا 2024", 130, 5, { cls: "متوسطة", seats: 5, transmission: "أوتوماتيك", year: 2024, fuel: "بنزين" }), car("bg-camry", "تويوتا كامري 2024", 180, 4, { cls: "كبيرة", seats: 5, transmission: "أوتوماتيك", year: 2024, fuel: "بنزين" }), car("bg-staria", "هيونداي ستاريا 2024", 260, 3, { cls: "عائلية 7 ركاب", seats: 7, transmission: "أوتوماتيك", year: 2024, fuel: "بنزين" }), car("bg-lc", "تويوتا لاند كروزر 2024", 450, 2, { cls: "دفع رباعي فاخرة", seats: 7, transmission: "أوتوماتيك", year: 2024, fuel: "بنزين" })] },
  { id: "biz-lumi", name: "Lumi", nameAr: "لومي لتأجير السيارات", category: "car_rental", sector: "تأجير سيارات", color: "#00A3E0",
    description: "شركة سعودية لتأجير السيارات بحجز رقمي كامل وتسليم سريع.",
    lat: 21.6274658, lng: 39.1350335, address: "طريق الأمير سلطان، النهضة، جدة", hours: "يومياً 8:00 ص – 11:00 م", website: "https://www.lumirental.com", phone: "+966920030030",
    highlights: ["حجز رقمي", "تسليم خلال ساعة", "سيارات كهربائية"],
    items: [car("lm-accent", "هيونداي أكسنت 2024", 90, 8, { cls: "اقتصادية", seats: 5, transmission: "أوتوماتيك", year: 2024, fuel: "بنزين" }), car("lm-corolla", "تويوتا كورولا 2024", 120, 6, { cls: "متوسطة", seats: 5, transmission: "أوتوماتيك", year: 2024, fuel: "بنزين" }), car("lm-tucson", "هيونداي توسان 2024", 200, 4, { cls: "دفع رباعي", seats: 5, transmission: "أوتوماتيك", year: 2024, fuel: "بنزين" }), car("lm-ioniq", "هيونداي أيونيك 5 (كهربائية)", 240, 2, { cls: "كهربائية", seats: 5, transmission: "أوتوماتيك", year: 2024, fuel: "كهرباء" })] },
  { id: "biz-hertz", name: "Hertz", nameAr: "هيرتز – فرع المطار", category: "car_rental", sector: "تأجير سيارات", color: "#FFD100",
    description: "فرع هيرتز في مطار الملك عبدالعزيز الدولي: استلام فور الوصول وإرجاع في أي فرع.",
    lat: 21.6839754, lng: 39.1634852, address: "مطار الملك عبدالعزيز الدولي، جدة", hours: "24 ساعة", website: "https://www.hertz.com", phone: "+966126856500",
    highlights: ["استلام من المطار", "إرجاع بفرع آخر", "برنامج Gold Plus"],
    items: [car("hz-sunny", "نيسان صني 2024", 100, 6, { cls: "اقتصادية", seats: 5, transmission: "أوتوماتيك", year: 2024, fuel: "بنزين" }), car("hz-altima", "نيسان ألتيما 2024", 170, 4, { cls: "كبيرة", seats: 5, transmission: "أوتوماتيك", year: 2024, fuel: "بنزين" }), car("hz-patrol", "نيسان باترول 2024", 420, 2, { cls: "دفع رباعي فاخرة", seats: 7, transmission: "أوتوماتيك", year: 2024, fuel: "بنزين" })] },
  { id: "biz-sixt", name: "SIXT", nameAr: "سيكست – فرع المطار", category: "car_rental", sector: "تأجير سيارات", color: "#FF5F00",
    description: "سيارات فاخرة وألمانية من فرع سيكست في مطار الملك عبدالعزيز الدولي.",
    lat: 21.6834, lng: 39.1642, address: "مطار الملك عبدالعزيز الدولي، جدة", hours: "24 ساعة", website: "https://www.sixt.com", phone: "+966126855555",
    highlights: ["سيارات فاخرة", "استلام من المطار", "سائق اختياري"],
    items: [car("sx-golf", "فولكس واجن جولف 2024", 140, 4, { cls: "مدمجة", seats: 5, transmission: "أوتوماتيك", year: 2024, fuel: "بنزين" }), car("sx-bmw3", "BMW الفئة الثالثة 2024", 350, 3, { cls: "فاخرة", seats: 5, transmission: "أوتوماتيك", year: 2024, fuel: "بنزين" }), car("sx-glc", "مرسيدس GLC 2024", 480, 2, { cls: "دفع رباعي فاخرة", seats: 5, transmission: "أوتوماتيك", year: 2024, fuel: "بنزين" })] },
  // ---------------------------------------------------------------- مستشفيات
  { id: "biz-kfgh", name: "King Fahd General Hospital", nameAr: "مستشفى الملك فهد العام بجدة", category: "hospital", sector: "مستشفى عام حكومي · وزارة الصحة", color: "#1B7F5C",
    description: "مستشفى مرجعي تابع لوزارة الصحة في جدة: طوارئ على مدار الساعة، عيادات خارجية في معظم التخصصات، مراكز للقلب والأورام والحروق وغسيل الكلى. "
      + "هذه الدائرة تعريفية للمستفيدين؛ المواعيد الرسمية عبر تطبيق «صحتي» أو الرقم الموحد 937، والحجز هنا لتنظيم الزيارة داخل ناس لايف. الموقع تقريبي ويمكن ضبطه من محرّر الدائرة.",
    lat: 21.5178, lng: 39.1834, address: "حي الأندلس، جدة", hours: "الطوارئ 24 ساعة · العيادات الخارجية الأحد – الخميس 8:00 ص – 4:00 م", phone: "937", website: "https://www.moh.gov.sa",
    highlights: ["طوارئ 24 ساعة", "مركز القلب", "مركز الأورام", "مركز الحروق", "غسيل الكلى", "عيادات خارجية"],
    items: [
      // ---- العيادات الخارجية (حجز موعد)
      clinic("kfgh-family", "عيادة طب الأسرة", "الكشف العام والتحويل للتخصصات ومتابعة الأمراض المزمنة", { times: ["08:00", "09:00", "10:00", "11:00", "13:00", "14:00", "15:00"], floor: "الدور الأول · العيادات الخارجية", capacity: 6 }),
      clinic("kfgh-internal", "عيادة الباطنية", "الضغط والسكري وأمراض الجهاز التنفسي والهضمي", { times: ["08:30", "09:30", "10:30", "11:30", "13:30", "14:30"], floor: "الدور الأول · العيادات الخارجية", capacity: 5 }),
      clinic("kfgh-surgery", "عيادة الجراحة العامة", "استشارات ما قبل العمليات ومتابعة ما بعدها", { times: ["09:00", "10:00", "11:00", "13:00", "14:00"], floor: "الدور الثاني", capacity: 4 }),
      clinic("kfgh-ortho", "عيادة العظام", "الكسور والمفاصل والعمود الفقري والإصابات الرياضية", { times: ["08:00", "09:00", "10:00", "11:00", "13:00", "14:00"], floor: "الدور الثاني", capacity: 5 }),
      clinic("kfgh-obgyn", "عيادة النساء والولادة", "متابعة الحمل وأمراض النساء", { times: ["08:00", "09:00", "10:00", "11:00", "12:00", "13:00"], floor: "مبنى النساء والولادة · الدور الأول", capacity: 5 }),
      clinic("kfgh-peds", "عيادة الأطفال", "الكشف العام للأطفال ومتابعة النمو والتطعيمات", { times: ["08:00", "09:00", "10:00", "11:00", "13:00", "14:00", "15:00"], floor: "مبنى الأطفال · الدور الأرضي", capacity: 6 }),
      clinic("kfgh-cardio", "عيادة القلب", "تخطيط القلب والإيكو ومتابعة ما بعد القسطرة", { times: ["09:00", "10:00", "11:00", "13:00"], floor: "مركز القلب · الدور الأول", capacity: 4 }),
      clinic("kfgh-onco", "عيادة الأورام", "التشخيص وخطط العلاج الكيميائي والمتابعة", { times: ["08:30", "09:30", "10:30", "11:30", "13:30"], floor: "مركز الأورام", capacity: 4 }),
      clinic("kfgh-nephro", "عيادة الكلى", "أمراض الكلى ومتابعة مرضى الغسيل", { times: ["09:00", "10:00", "11:00", "13:00"], floor: "الدور الثالث", capacity: 4 }),
      clinic("kfgh-uro", "عيادة المسالك البولية", "الحصوات والبروستاتا والتهابات المسالك", { times: ["09:00", "10:00", "11:00", "14:00"], floor: "الدور الثاني", capacity: 4 }),
      clinic("kfgh-ent", "عيادة الأنف والأذن والحنجرة", "السمع والجيوب الأنفية واللوزتين", { times: ["08:00", "09:00", "10:00", "11:00", "13:00"], floor: "الدور الأول", capacity: 5 }),
      clinic("kfgh-eye", "عيادة العيون", "فحص النظر والشبكية والمياه البيضاء", { times: ["08:00", "09:00", "10:00", "11:00", "13:00", "14:00"], floor: "الدور الأول", capacity: 5 }),
      clinic("kfgh-derma", "عيادة الجلدية", "الأمراض الجلدية والحساسية", { times: ["09:00", "10:00", "11:00", "13:00"], floor: "الدور الثاني", capacity: 5 }),
      clinic("kfgh-neuro", "عيادة الأعصاب", "الصداع والصرع والجلطات ومتابعتها", { times: ["09:00", "10:00", "11:00", "13:00"], floor: "الدور الثالث", capacity: 4 }),
      clinic("kfgh-psych", "عيادة الطب النفسي", "الاستشارات النفسية والمتابعة الدوائية بخصوصية تامة", { times: ["09:00", "10:00", "11:00", "13:00", "14:00"], floor: "الدور الثالث", capacity: 4 }),
      clinic("kfgh-endo", "عيادة الغدد الصماء والسكري", "السكري والغدة الدرقية والسمنة", { times: ["08:30", "09:30", "10:30", "11:30", "13:30"], floor: "الدور الأول", capacity: 5 }),
      clinic("kfgh-gastro", "عيادة الجهاز الهضمي والمناظير", "القولون والكبد والمناظير التشخيصية", { times: ["09:00", "10:00", "11:00", "13:00"], floor: "الدور الثاني", capacity: 4 }),
      clinic("kfgh-chest", "عيادة الصدرية", "الربو والانسداد الرئوي واضطرابات النوم", { times: ["09:00", "10:00", "11:00", "13:00"], floor: "الدور الثاني", capacity: 4 }),
      clinic("kfgh-dental", "عيادة الأسنان", "الكشف والحشوات والخلع وعلاج اللثة", { times: ["08:00", "09:00", "10:00", "11:00", "13:00", "14:00", "15:00"], floor: "مبنى الأسنان", capacity: 6 }),
      clinic("kfgh-physio", "العلاج الطبيعي والتأهيل", "جلسات تأهيل بعد الإصابات والعمليات (بتحويل من الطبيب)", { times: ["08:00", "09:00", "10:00", "11:00", "13:00", "14:00"], floor: "مبنى التأهيل · الدور الأرضي", capacity: 8, minutes: 40 }),
      clinic("kfgh-nutrition", "عيادة التغذية العلاجية", "خطط غذائية لمرضى السكري والكلى والسمنة", { times: ["09:00", "10:00", "11:00", "13:00"], floor: "الدور الأول", capacity: 5, minutes: 30 }),
      // ---- الأقسام والخدمات (تعريفية)
      info("kfgh-er", "الطوارئ والحوادث", "استقبال الحالات الطارئة على مدار الساعة بنظام الفرز حسب الخطورة؛ الحالات الحرجة تُعالج فوراً. للإسعاف اتصل 997.", { hours: "24 ساعة", location: "مدخل الطوارئ · الجهة الشمالية", phone: "997" }),
      info("kfgh-icu", "العناية المركزة", "وحدات العناية المركزة للكبار والأطفال وحديثي الولادة. الزيارة محدودة بمرافق واحد في الأوقات المحددة.", { hours: "الزيارة 4:00 م – 6:00 م", location: "الدور الرابع" }),
      info("kfgh-lab", "المختبر ونتائج التحاليل", "سحب العينات صباحاً للعيادات الخارجية، والنتائج تظهر في تطبيق «صحتي» أو تُستلم من مكتب النتائج ببطاقة الهوية.", { hours: "الأحد – الخميس 7:00 ص – 3:00 م · الطوارئ 24 ساعة", location: "الدور الأرضي" }),
      info("kfgh-blood", "بنك الدم والتبرع بالدم", "التبرع متاح لمن تجاوز 18 عاماً ووزنه فوق 50 كجم وبصحة جيدة؛ أحضر الهوية الوطنية. التبرع يستغرق نحو 30 دقيقة.", { hours: "يومياً 8:00 ص – 8:00 م", location: "الدور الأرضي · بجوار المختبر" }),
      info("kfgh-radiology", "الأشعة والتصوير الطبي", "أشعة سينية، موجات صوتية، أشعة مقطعية، رنين مغناطيسي. المواعيد بتحويل من الطبيب، وتُستلم الأقراص من مكتب الأشعة.", { hours: "الأحد – الخميس 8:00 ص – 4:00 م · الطوارئ 24 ساعة", location: "الدور الأرضي" }),
      info("kfgh-pharmacy", "الصيدلية وصرف الأدوية", "صرف أدوية العيادات الخارجية والطوارئ بموجب الوصفة الإلكترونية؛ الأدوية المزمنة تُصرف لثلاثة أشهر.", { hours: "الأحد – الخميس 8:00 ص – 8:00 م · صيدلية الطوارئ 24 ساعة", location: "الدور الأرضي" }),
      info("kfgh-dialysis", "وحدة غسيل الكلى", "جلسات غسيل الكلى الدموي على ثلاث فترات يومياً وفق جدول ثابت لكل مريض.", { hours: "السبت – الخميس 7:00 ص – 11:00 م", location: "الدور الثالث" }),
      info("kfgh-burn", "مركز الحروق", "مركز متخصص لعلاج الحروق وجراحات الترميم والتجميل التالية لها.", { hours: "24 ساعة", location: "مبنى الحروق" }),
      info("kfgh-maternity", "الولادة وحديثي الولادة", "غرف الولادة الطبيعية والقيصرية ووحدة العناية بحديثي الولادة. يُسمح بمرافقة واحدة.", { hours: "24 ساعة", location: "مبنى النساء والولادة" }),
      info("kfgh-reports", "التقارير الطبية والإجازات المرضية", "تُصدر التقارير والإجازات المرضية إلكترونياً عبر «صحتي» بعد اعتماد الطبيب؛ الطلبات الخاصة من مكتب التقارير.", { hours: "الأحد – الخميس 8:00 ص – 2:00 م", location: "الدور الأول · مكتب التقارير الطبية" }),
      info("kfgh-patients", "شؤون المرضى وخدمة المستفيدين", "الشكاوى والاقتراحات والاستفسارات وتنسيق الزيارات؛ يمكنك أيضاً مراسلة الدائرة هنا.", { hours: "الأحد – الخميس 8:00 ص – 4:00 م", location: "الدور الأرضي · المدخل الرئيسي", phone: "937" }),
      info("kfgh-social", "الخدمة الاجتماعية", "دعم المرضى وأسرهم، تنسيق الجهات الخيرية، وحالات الإيواء والعنف الأسري.", { hours: "الأحد – الخميس 8:00 ص – 4:00 م", location: "الدور الأول" }),
      info("kfgh-vaccines", "التطعيمات", "تطعيمات الأطفال حسب الجدول الوطني وتطعيمات الكبار والحجاج.", { hours: "الأحد – الخميس 8:00 ص – 2:00 م", location: "مبنى الأطفال · الدور الأرضي" }),
      info("kfgh-visiting", "مواعيد الزيارة", "زيارة المرضى المنوّمين من الساعة 4 عصراً حتى 9 مساءً بزائرَين كحد أقصى، ويُمنع دخول الأطفال دون 12 عاماً إلى الأجنحة.", { hours: "يومياً 4:00 م – 9:00 م" }),
      info("kfgh-ambulance", "الإسعاف والنقل الطبي", "للحالات الطارئة اتصل بالهلال الأحمر 997. النقل الطبي بين المستشفيات يُنسَّق عبر قسم الطوارئ.", { hours: "24 ساعة", phone: "997" }),
      info("kfgh-facilities", "المرافق: مواقف، مصلى، كافتيريا، صراف", "مواقف مجانية للمراجعين، مصلى للرجال والنساء في الدور الأرضي، كافتيريا ومقهى بجوار المدخل الرئيسي، وصراف آلي.", { hours: "24 ساعة", location: "المدخل الرئيسي" }),
      info("kfgh-volunteer", "التطوع والتبرع", "برامج تطوعية لدعم المرضى، وتبرعات عينية للمرضى المحتاجين عبر قسم الخدمة الاجتماعية.", { hours: "الأحد – الخميس 9:00 ص – 3:00 م", location: "مكتب التطوع · الدور الأول" }),
    ] },

];
