// بيانات تمهيد السوق (server/market_seed.js): بائعون وهميون بأسماء وسِيَر واقعية، ومنتجات وخدمات في كل تصنيفات السوق
// موزّعة على أحياء حقيقية في جدة والرياض والدمام والخبر. الصور مضمّنة في الموقع تحت /seed/market/<slug>.jpg
// (تُجلب مرة واحدة أثناء التطوير وتُنشر مع حزمة الويب). الأسعار بالريال، وتُخزَّن بالهللة.

// الأحياء: [lat, lng]
export const AREAS = {
  // جدة
  "الروضة، جدة": [21.562, 39.165], "الحمراء، جدة": [21.531, 39.166], "السلامة، جدة": [21.592, 39.145], "النعيم، جدة": [21.608, 39.149],
  "الشاطئ، جدة": [21.622, 39.108], "أبحر الشمالية، جدة": [21.77, 39.107], "الصفا، جدة": [21.598, 39.214], "المرجان، جدة": [21.658, 39.107],
  "الزهراء، جدة": [21.578, 39.142], "الخالدية، جدة": [21.556, 39.15], "النزهة، جدة": [21.606, 39.183], "البساتين، جدة": [21.654, 39.142],
  "الفيصلية، جدة": [21.567, 39.2], "الأندلس، جدة": [21.534, 39.178], "البلد، جدة": [21.486, 39.187], "الربوة، جدة": [21.598, 39.188],
  "المحمدية، جدة": [21.63, 39.134], "الحمدانية، جدة": [21.64, 39.23],
  // الرياض
  "العليا، الرياض": [24.695, 46.685], "النخيل، الرياض": [24.745, 46.63], "الملقا، الرياض": [24.81, 46.61], "الياسمين، الرياض": [24.825, 46.64],
  "حطين، الرياض": [24.77, 46.59], "الورود، الرياض": [24.72, 46.66], "الربيع، الرياض": [24.8, 46.67], "السليمانية، الرياض": [24.7, 46.7],
  "الروضة، الرياض": [24.72, 46.77], "الرحمانية، الرياض": [24.73, 46.635], "النرجس، الرياض": [24.85, 46.65],
  // الدمام والخبر
  "الشاطئ، الدمام": [26.45, 50.11], "الفيصلية، الدمام": [26.413, 50.102], "الريان، الدمام": [26.4, 50.08], "الجلوية، الدمام": [26.43, 50.1],
  "عبدالله فؤاد، الدمام": [26.37, 50.15], "العقربية، الخبر": [26.29, 50.2], "الراكة، الخبر": [26.33, 50.205], "الثقبة، الخبر": [26.275, 50.21],
};

// البائعون: nickname يطابق قواعد النواة (حروف صغيرة وأرقام وشرطة سفلية)
export const SELLERS = [
  { nick: "um_fahad_kitchen", bio: "مطبخ أم فهد: أكل بيت على أصوله، صواني كبسة ومندي ومعجنات بالطلب المسبق. التوصيل داخل جدة.", area: "الصفا، جدة", skills: ["طبخ منزلي", "معجنات"], offerings: ["صواني ولائم", "توصيل"], looking: ["زبائن دائمين"] },
  { nick: "saleh_roasts", bio: "صالح، أحمّص القهوة في بيتي منذ ٢٠٢١. حبوب إثيوبية وكولومبية، تحميص فاتح ووسط، وأشرح لك طريقة التخمير.", area: "الروضة، جدة", skills: ["تحميص قهوة", "V60"], offerings: ["حبوب مختصة", "ورش تخمير"], looking: ["مقاهي صغيرة"] },
  { nick: "noura_crochet", bio: "نورة، كروشيه وأعمال يدوية بطلبات خاصة: بطانيات أطفال، شنط، ودمى. كل قطعة تُصنع بعد الطلب.", area: "الياسمين، الرياض", skills: ["كروشيه", "تطريز"], offerings: ["هدايا مواليد"], looking: ["تعاون مع محلات هدايا"] },
  { nick: "lens_rayan", bio: "ريان، مصوّر منتجات ومناسبات في جدة. أستوديو صغير في الشاطئ وتصوير خارجي. تسليم خلال ٤٨ ساعة.", area: "الشاطئ، جدة", skills: ["تصوير منتجات", "تعديل صور"], offerings: ["جلسات تصوير"], looking: ["متاجر إلكترونية"] },
  { nick: "abu_saud_ac", bio: "أبو سعود، فني تكييف وسباكة بخبرة ١٢ سنة. أوصل خلال ساعة داخل شمال جدة، وضمان على الشغل شهر.", area: "النزهة، جدة", skills: ["تكييف", "سباكة", "كهرباء منزلية"], offerings: ["صيانة منزلية"], looking: ["عقود صيانة سنوية"] },
  { nick: "hind_gifts", bio: "هند، بوكسات هدايا مغلّفة بذوق لكل مناسبة: تخرج، مواليد، عيد ميلاد. تخصيص الاسم مجاناً.", area: "الملقا، الرياض", skills: ["تغليف", "تنسيق هدايا"], offerings: ["بوكسات جاهزة", "طلبات خاصة"], looking: ["شركات تبحث عن هدايا موظفين"] },
  { nick: "wasel_express", bio: "فيصل، توصيل سريع داخل جدة بسيارتي الخاصة. طرود، أغراض بقالة، أدوية، وتوصيل المطار. متاح من ٨ صباحاً إلى ١٢ ليلاً.", area: "الحمدانية، جدة", skills: ["توصيل", "مشاوير"], offerings: ["توصيل خلال ساعة"], looking: ["متاجر تحتاج مندوب"] },
  { nick: "mariam_tutor", bio: "مريم، معلمة رياضيات وفيزياء للمرحلة الثانوية. تدريس فردي حضوري في الدمام أو عن بُعد، وتحضير لاختبار القدرات.", area: "الفيصلية، الدمام", skills: ["رياضيات", "فيزياء", "قدرات"], offerings: ["دروس خصوصية"], looking: ["طلاب ثانوي"] },
  { nick: "dates_alqassim", bio: "عبدالله من بريدة. تمور سكري وخلاص ومجدول من مزرعة العائلة، مباشرة من القصيم إلى الرياض أسبوعياً.", area: "الرحمانية، الرياض", skills: ["تمور"], offerings: ["تمور بالجملة والتجزئة"], looking: ["موزعين"] },
  { nick: "lama_candles", bio: "لمى، شموع صويا وريزن يدوي. روائح مركّزة ومصبوبة يدوياً في الحمراء، وأصنع تشكيلات خاصة للأعراس.", area: "الحمراء، جدة", skills: ["شموع", "ريزن"], offerings: ["توزيعات أعراس"], looking: ["منسّقات مناسبات"] },
  { nick: "khalid_detailing", bio: "خالد، تلميع وتنظيف سيارات متنقل في الرياض. أجيك عند بيتك أو مكتبك بمعداتي. نانو سيراميك وتنظيف داخلي بالبخار.", area: "حطين، الرياض", skills: ["تلميع سيارات", "نانو سيراميك"], offerings: ["خدمة متنقلة"], looking: ["أساطيل شركات"] },
  { nick: "reem_cakes", bio: "ريم، كيك وحلويات بالطلب في الخبر. كيك مواليد وتخرج، كوكيز، وبراونيز. الطلب قبل ٤٨ ساعة.", area: "العقربية، الخبر", skills: ["كيك", "حلويات"], offerings: ["كيك مناسبات"], looking: ["مقاهي تحتاج مورد حلويات"] },
  { nick: "ahmad_it_fix", bio: "أحمد، صيانة لابتوبات وجوالات في جدة. تغيير شاشات وبطاريات، تنظيف وترقية، واسترجاع بيانات. فحص مجاني.", area: "الفيصلية، جدة", skills: ["صيانة لابتوب", "صيانة جوال"], offerings: ["استلام وتوصيل"], looking: ["مكاتب صغيرة"] },
  { nick: "sara_makeup", bio: "سارة، خبيرة مكياج ونقش حناء في الدمام. مكياج عرايس ومناسبات في بيتك، وحناء خليجية وهندية.", area: "الشاطئ، الدمام", skills: ["مكياج", "حناء"], offerings: ["مكياج عرايس"], looking: ["صالونات"] },
  { nick: "turki_drone", bio: "تركي، تصوير جوي بالدرون وفيديو للعقارات والفعاليات في الرياض. مرخّص من الطيران المدني.", area: "النخيل، الرياض", skills: ["درون", "مونتاج"], offerings: ["تصوير عقارات"], looking: ["مكاتب عقار"] },
  { nick: "oud_alharamain", bio: "ماجد، عود وبخور ودهن عود من محلنا في البلد. عود كمبودي وهندي ومعطّر مخلّط على طريقتنا.", area: "البلد، جدة", skills: ["عود", "بخور"], offerings: ["عطور شرقية"], looking: ["زبائن الجملة"] },
  { nick: "yara_pottery", bio: "يارا، فخار وسيراميك مشغول يدوياً على العجلة. أكواب وصحون ومزهريات، وورش للمبتدئين في الروضة.", area: "الروضة، الرياض", skills: ["فخار", "سيراميك"], offerings: ["ورش فخار"], looking: ["مقاهي تريد أكواب خاصة"] },
  { nick: "fahad_moving", bio: "فهد، دينا ونقل أثاث وأغراض داخل جدة وبين جدة ومكة. عمّال فك وتركيب، وتغليف.", area: "البساتين، جدة", skills: ["نقل أثاث", "فك وتركيب"], offerings: ["نقل عفش"], looking: ["مكاتب عقار"] },
  { nick: "amal_arabic", bio: "أمل، معلمة لغة عربية وتحفيظ قرآن بإجازة. دروس للأطفال والكبار وغير الناطقين بالعربية، حضوري في الرياض أو أونلاين.", area: "الورود، الرياض", skills: ["تحفيظ", "لغة عربية"], offerings: ["دروس أونلاين"], looking: ["طلاب"] },
  { nick: "coffee_corner_dmm", bio: "نواف، أدوات القهوة المختصة في الدمام: كيمكس، V60، مطاحن، وموازين. وأبيع محاصيل مختارة من محامص محلية.", area: "الريان، الدمام", skills: ["قهوة مختصة"], offerings: ["أدوات تخمير"], looking: ["شراكة مع محامص"] },
  { nick: "hessa_abayas", bio: "حصة، تفصيل عبايات وجلابيات على المقاس في السلامة. أقمشة كوري وياباني، وتشكيلة جاهزة.", area: "السلامة، جدة", skills: ["خياطة", "تفصيل"], offerings: ["عبايات على المقاس"], looking: ["زبونات دائمات"] },
  { nick: "omar_plants", bio: "عمر، نباتات داخلية وأحواض من مشتلي الصغير في النرجس. أساعدك تختار النبتة المناسبة لإضاءة بيتك.", area: "النرجس، الرياض", skills: ["نباتات", "تنسيق حدائق"], offerings: ["نباتات داخلية"], looking: ["مكاتب تبي تخضير"] },
  { nick: "bassam_design", bio: "بسام، مصمم جرافيك: هويات بصرية، شعارات، منيو مطاعم، ومحتوى سوشيال. ١٠ سنوات خبرة في جدة.", area: "الزهراء، جدة", skills: ["تصميم شعارات", "هوية بصرية", "سوشيال ميديا"], offerings: ["تصميم"], looking: ["مشاريع ناشئة"] },
  { nick: "ghada_flowers", bio: "غادة، تنسيق ورد طبيعي في الخبر. باقات يومية وبوكسات ورد وتنسيق طاولات المناسبات.", area: "الراكة، الخبر", skills: ["تنسيق ورد"], offerings: ["باقات وتوصيل"], looking: ["قاعات أفراح"] },
  { nick: "coach_ali_fit", bio: "علي، مدرب لياقة معتمد في الدمام. برامج تدريب شخصية في النادي أو البيت، وخطط تغذية.", area: "الجلوية، الدمام", skills: ["تدريب شخصي", "تغذية"], offerings: ["برامج لياقة"], looking: ["متدربين جادين"] },
  { nick: "english_with_dana", bio: "دانة، معلمة إنجليزي ومحادثة، خريجة لغويات من بريطانيا. تحضير آيلتس وستيب ومحادثة للكبار.", area: "الربيع، الرياض", skills: ["إنجليزي", "آيلتس"], offerings: ["محادثة أونلاين"], looking: ["موظفين يريدون تطوير لغتهم"] },
  { nick: "books_jeddah", bio: "ثامر، كتب مستعملة بحالة ممتازة: روايات، تطوير ذات، وكتب جامعية. أبيع وأشتري وأبادل في الأندلس.", area: "الأندلس، جدة", skills: ["كتب"], offerings: ["كتب مستعملة"], looking: ["قرّاء"] },
];

// المنتجات والخدمات: slug فريد، seller من القائمة أعلاه، price بالريال، photo وسوم الصورة
export const LISTINGS = [
  // ---- مطبخ أم فهد (طعام)
  { slug: "kabsa-tray-large", sub: "meals", seller: "um_fahad_kitchen", kind: "product", category: "food", title: "صينية كبسة دجاج كبيرة (تكفي ٦)", price: 180, photo: "kabsa,rice,chicken", days: 3,
    desc: "كبسة دجاج على الطريقة الحجازية بأرز بسمتي وبهارات مطحونة طازجة، مع سلطة وشطة دقوس. الطلب قبل ٦ ساعات، والتوصيل داخل جدة ٢٠ ريال." },
  { slug: "mandi-lamb-tray", sub: "meals", seller: "um_fahad_kitchen", kind: "product", category: "food", title: "صينية مندي لحم (ذبيحة نصف)", price: 650, photo: "lamb,rice,arabic food", days: 9,
    desc: "لحم نعيمي طري على أرز مندي بنكهة الدخان الأصلية. مناسبة للولائم والعزايم، وتكفي ١٥ شخصاً. نضيف اللقيمات مجاناً للطلبات فوق ٥٠٠ ريال." },
  { slug: "sambosa-box-50", sub: "pastries", seller: "um_fahad_kitchen", kind: "product", category: "food", title: "سمبوسة جاهزة للقلي، ٥٠ حبة", price: 55, photo: "samosa,fried,food", days: 14,
    desc: "سمبوسة لحم أو جبن أو خضار، مبرّدة ومغلّفة بإحكام. تُقلى في ٣ دقائق. متوفرة طوال السنة وبكميات كبيرة قبل رمضان." },
  { slug: "home-breakfast-box", sub: "meals", seller: "um_fahad_kitchen", kind: "product", category: "food", title: "بوكس فطور شعبي لشخصين", price: 75, photo: "breakfast,arabic,foul", days: 1,
    desc: "فول بالسمن، شكشوكة، معصوب بالموز والعسل، خبز تميس طازج، وشاي أحمر. يوصل ساخناً من ٧ إلى ١١ صباحاً." },
  { slug: "weekly-meal-plan", sub: "subscriptions", seller: "um_fahad_kitchen", kind: "service", category: "food", title: "اشتراك وجبات أسبوعي (غداء ٥ أيام)", price: 320, photo: "meal prep,lunch box", days: 6,
    desc: "غداء بيتي يوصلك من الأحد للخميس: طبق رئيسي وسلطة وحلى خفيف. تختار الأطباق من قائمة الأسبوع، ونراعي الحمية إن أردت." },
  // ---- صالح للتحميص (قهوة)
  { slug: "ethiopia-guji-250", sub: "beans", seller: "saleh_roasts", kind: "product", category: "coffee", title: "قهوة إثيوبيا قوجي، تحميص فاتح ٢٥٠ غ", price: 68, photo: "coffee beans,roasted", days: 2,
    desc: "محصول موسم ٢٠٢٦، معالجة مغسولة، نكهات توت وياسمين وشاي أسود. محمّصة خلال الأسبوع، ومناسبة للفلتر والكيمكس." },
  { slug: "colombia-huila-1kg", sub: "beans", seller: "saleh_roasts", kind: "product", category: "coffee", title: "قهوة كولومبيا هويلا، ١ كيلو للإسبريسو", price: 190, photo: "espresso,coffee bag", days: 5,
    desc: "تحميص وسط متوازن بنكهات الكراميل والشوكولاتة، مثالي للإسبريسو والمكائن المنزلية. سعر خاص للمقاهي عند طلب ٥ كيلو فأكثر." },
  { slug: "saudi-coffee-blend", sub: "beans", seller: "saleh_roasts", kind: "product", category: "coffee", title: "قهوة سعودية مطحونة مع هيل وزعفران ٥٠٠ غ", price: 85, photo: "arabic coffee,dallah", days: 11,
    desc: "خلطة بيتنا: بن أخضر محمّص خفيف مع هيل حبّ وزعفران ومسمار. جاهزة للدلّة مباشرة. عبوة محكمة تحافظ على الريحة شهراً." },
  { slug: "brewing-workshop", sub: "workshops", seller: "saleh_roasts", kind: "service", category: "coffee", title: "ورشة تخمير قهوة مختصة في بيتك (٣ ساعات)", price: 350, photo: "pour over,coffee brewing", days: 8,
    desc: "ورشة عملية لك ولأصدقائك حتى ٦ أشخاص: أساسيات الطحن والنسب والحرارة، وتجربة V60 وفرنش برس وأيروبرس. الأدوات والقهوة عليّ." },
  { slug: "cold-brew-bottles", sub: "drinks", seller: "saleh_roasts", kind: "product", category: "coffee", title: "كولد برو مركّز، ٦ قوارير × ٢٥٠ مل", price: 90, photo: "cold brew,coffee bottle", days: 4,
    desc: "منقوع ١٨ ساعة من حبوب برازيلية، يُخفّف بالماء أو الحليب. يبقى أسبوعين في الثلاجة. التوصيل مبرّد داخل جدة." },
  // ---- نورة كروشيه (أعمال يدوية)
  { slug: "baby-blanket-crochet", sub: "crochet", seller: "noura_crochet", kind: "product", category: "handmade", title: "بطانية مواليد كروشيه بالاسم", price: 220, photo: "crochet,blanket,baby", days: 2,
    desc: "بطانية ٨٠×١٠٠ سم من خيط قطن ناعم مضاد للحساسية، بالألوان التي تختارها مع تطريز اسم المولود. مدة التنفيذ ٧ أيام." },
  { slug: "crochet-tote-bag", sub: "crochet", seller: "noura_crochet", kind: "product", category: "handmade", title: "شنطة كروشيه صيفية كبيرة", price: 140, photo: "crochet bag,tote", days: 13,
    desc: "شنطة يومية بمقبض جلد طبيعي وبطانة قماش، تتحمل الوزن. متوفرة بالبيج والزيتي والأزرق، ونعمل ألواناً بالطلب." },
  { slug: "amigurumi-doll", sub: "crochet", seller: "noura_crochet", kind: "product", category: "handmade", title: "دمية أميغورومي بشخصية طفلك", price: 160, photo: "amigurumi,crochet toy", days: 20,
    desc: "دمية محبوكة يدوياً بطول ٢٥ سم تشبه ملامح وملابس طفلك من صورة ترسلينها. حشوة آمنة ومناسبة من عمر ٣ سنوات." },
  { slug: "crochet-class-online", sub: "crochet", seller: "noura_crochet", kind: "service", category: "handmade", title: "كورس كروشيه للمبتدئات (٤ جلسات أونلاين)", price: 250, photo: "crochet,yarn,hands", days: 7,
    desc: "من الصفر حتى أول قطعة مكتملة. نتعلّم الغرز الأساسية وقراءة الباترون، والعدّة ترسل لك مع أول جلسة داخل الرياض." },
  { slug: "macrame-wall-hanging", sub: "crochet", seller: "noura_crochet", kind: "product", category: "handmade", title: "معلّقة مكرمية للجدار ٦٠ سم", price: 185, photo: "macrame,wall hanging", days: 17,
    desc: "مكرمية قطن طبيعي على عصا خشب مخروطة، تصميم بوهيمي يناسب غرف النوم والمداخل. أقبل مقاسات خاصة حتى ١٢٠ سم." },
  // ---- ريان مصوّر (تصوير)
  { slug: "product-photo-session", sub: "products", seller: "lens_rayan", kind: "service", category: "photo", title: "تصوير منتجات لمتجرك، ٢٠ منتجاً", price: 900, photo: "product photography,studio", days: 1,
    desc: "خلفية بيضاء أو ستايل لايف ستايل، ٣ زوايا لكل منتج مع تعديل الألوان وقص الخلفية. التسليم خلال ٤٨ ساعة بصيغ جاهزة لسلة وزد." },
  { slug: "wedding-photo-package", sub: "events", seller: "lens_rayan", kind: "service", category: "photo", title: "تغطية زواج كاملة، مصوّر ومصوّرة", price: 4500, photo: "wedding,photography", days: 12,
    desc: "٦ ساعات تغطية للقسمين، ٣٠٠ صورة معدّلة وألبوم مطبوع ٣٠×٣٠. طاقم نسائي للقسم النسائي، ونسلّم مختارات خلال ٤٨ ساعة." },
  { slug: "family-outdoor-shoot", sub: "portraits", seller: "lens_rayan", kind: "service", category: "photo", title: "جلسة تصوير عائلية على الكورنيش (ساعة)", price: 600, photo: "family,portrait,beach", days: 4,
    desc: "جلسة غروب على كورنيش جدة أو في موقع تختاره، ٤٠ صورة معدّلة بدقة عالية. مناسبة للمواليد والتخرج وذكرى الزواج." },
  { slug: "photo-editing-batch", sub: "editing", seller: "lens_rayan", kind: "service", category: "photo", title: "تعديل واحترافي لصورك، ٥٠ صورة", price: 300, photo: "photo editing,laptop", days: 19,
    desc: "تصحيح ألوان وإضاءة وإزالة العيوب لصور جوالك أو كاميرتك. ترسل الصور عبر رابط، وتستلمها خلال ٣ أيام." },
  { slug: "fine-art-prints", sub: "prints", seller: "lens_rayan", kind: "product", category: "photo", title: "لوحة مطبوعة من صور جدة القديمة ٥٠×٧٠", price: 240, photo: "print,frame,wall art", days: 25,
    desc: "من مجموعتي الخاصة للبلد والروشان، طباعة أرشيفية على ورق قطني ببرواز خشب أسود. تُشحن لكل المملكة." },
  // ---- أبو سعود صيانة (خدمات)
  { slug: "ac-cleaning-split", sub: "maintenance", seller: "abu_saud_ac", kind: "service", category: "services", title: "تنظيف مكيف سبليت شامل الوحدة الخارجية", price: 150, photo: "air conditioner,repair,technician", days: 2,
    desc: "غسيل الفلاتر والمبخّر بالضغط، تنظيف الوحدة الخارجية، وفحص الفريون. ٣ مكيفات فأكثر بسعر ١٢٠ للواحد. خدمة في اليوم نفسه." },
  { slug: "plumbing-visit", sub: "maintenance", seller: "abu_saud_ac", kind: "service", category: "services", title: "زيارة سباكة: تسريب أو انسداد أو تركيب", price: 120, photo: "plumber,pipe,repair", days: 6,
    desc: "كشف وإصلاح تسريبات الخلاطات والسيفونات، تسليك المجاري بجهاز الضغط، وتركيب سخانات. السعر يشمل أول ساعة عمل بدون قطع." },
  { slug: "ac-freon-refill", sub: "maintenance", seller: "abu_saud_ac", kind: "service", category: "services", title: "تعبئة فريون مكيف مع كشف التسريب", price: 220, photo: "hvac,gauge,technician", days: 15,
    desc: "فحص ضغط الغاز بالعدّاد، إصلاح التسريب إن وُجد، وتعبئة فريون R410 أو R22. ضمان ٣٠ يوماً على التعبئة." },
  { slug: "electric-fix", sub: "maintenance", seller: "abu_saud_ac", kind: "service", category: "services", title: "كهربائي منزلي: قواطع وإنارة وأفياش", price: 100, photo: "electrician,wiring", days: 22,
    desc: "تغيير القواطع والأفياش والمفاتيح، تركيب ثريات وسبوتات، وحل مشاكل الانقطاع. متوفر مساءً وفي الإجازات." },
  // ---- هند هدايا (هدايا)
  { slug: "graduation-gift-box", sub: "boxes", seller: "hind_gifts", kind: "product", category: "gifts", title: "بوكس تخرج فاخر بالاسم", price: 260, photo: "gift box,ribbon", days: 3,
    desc: "بوكس خشب مطبوع بالاسم وسنة التخرج: دفتر جلد، قلم معدني، شمعة، بطاقة تهنئة بخط اليد وشوكولاتة بلجيكية. التوصيل داخل الرياض في اليوم نفسه." },
  { slug: "newborn-gift-set", sub: "boxes", seller: "hind_gifts", kind: "product", category: "gifts", title: "طقم هدية مولود: بطانية وقماط وبطاقة", price: 195, photo: "baby gift,newborn", days: 10,
    desc: "بطانية موسلين، قماط قطن عضوي، شرابات، ولعبة قماشية، مرتبة في سلة خوص مع بطاقة تهنئة. نضيف اسم المولود بالتطريز بـ ٣٠ ريالاً." },
  { slug: "corporate-gift-boxes", sub: "corporate", seller: "hind_gifts", kind: "service", category: "gifts", title: "هدايا موظفين للشركات (٢٠ بوكس فأكثر)", price: 120, photo: "corporate gift,packaging", days: 8,
    desc: "السعر للبوكس الواحد: تغليف بشعار شركتكم، محتويات تختارونها من قائمتنا (تمور، شموع، أكواب، حلويات)، والتوصيل لمقر الشركة." },
  { slug: "personalized-mug", sub: "personalized", seller: "hind_gifts", kind: "product", category: "gifts", title: "كوب سيراميك بطباعة صورة أو اسم", price: 45, photo: "mug,personalized,ceramic", days: 16,
    desc: "طباعة حرارية عالية الجودة تتحمل الغسيل. ترسل الصورة أو النص، ويجهز خلال يومين. عرض ٣ أكواب بـ ١٢٠." },
  // ---- فيصل توصيل (توصيل)
  { slug: "delivery-1hour-jeddah", sub: "parcels", seller: "wasel_express", kind: "service", category: "delivery", title: "توصيل طرد داخل جدة خلال ساعة", price: 25, photo: "delivery,courier,car", days: 1,
    desc: "استلام من أي مكان في جدة وتوصيل خلال ساعة داخل الحي المجاور، وساعتين لأطراف المدينة. أرسل الموقع واسم المستلم فقط." },
  { slug: "grocery-run", sub: "groceries", seller: "wasel_express", kind: "service", category: "delivery", title: "مشوار بقالة أو صيدلية بقائمة مشترياتك", price: 30, photo: "grocery,shopping bags", days: 5,
    desc: "أرسل قائمتك وأشتريها من المتجر الذي تفضّله وأوصلها لبابك. أجرة المشوار ٣٠ ريالاً، والمشتريات بالفاتورة." },
  { slug: "airport-luggage", sub: "airport", seller: "wasel_express", kind: "service", category: "delivery", title: "توصيل شنط للمطار أو منه", price: 80, photo: "luggage,airport,suitcase", days: 12,
    desc: "أستلم شنطك من بيتك وأوصلها لصالة المغادرة، أو أستقبلها من الوصول وأوصلها لبيتك. مفيد للحجاج والمعتمرين والعائلات الكبيرة." },
  { slug: "store-courier-monthly", sub: "parcels", seller: "wasel_express", kind: "service", category: "delivery", title: "مندوب توصيل شهري لمتجرك (٦٠ طلباً)", price: 1200, photo: "delivery van,packages", days: 18,
    desc: "باقة شهرية للمتاجر الصغيرة: ٦٠ توصيلة داخل جدة بتتبع مباشر وتحصيل نقدي إن أردت. الطلبات الإضافية بـ ١٨ ريالاً." },
  // ---- مريم معلمة (خدمات)
  { slug: "math-private-lesson", sub: "education", seller: "mariam_tutor", kind: "service", category: "services", title: "درس رياضيات خصوصي ثانوي (ساعة ونصف)", price: 150, photo: "math,tutoring,whiteboard", days: 2,
    desc: "شرح مبسّط لمنهج المسارات مع حل تمارين الكتاب والاختبارات السابقة. حضوري في الدمام أو عبر زوم بسبورة تفاعلية." },
  { slug: "qudurat-prep-course", sub: "education", seller: "mariam_tutor", kind: "service", category: "services", title: "دورة تأسيس قدرات كمّي (١٢ ساعة)", price: 850, photo: "exam,study,students", days: 9,
    desc: "٨ جلسات تغطي كل أقسام الكمّي مع بنك أسئلة محدّث واختبارات محاكية. مجموعات صغيرة حتى ٤ طالبات، أو فردي بسعر مختلف." },
  { slug: "physics-lab-help", sub: "education", seller: "mariam_tutor", kind: "service", category: "services", title: "مراجعة فيزياء قبل الاختبار (٣ ساعات)", price: 280, photo: "physics,science,lesson", days: 21,
    desc: "جلسة مكثّفة نلخّص فيها الفصل ونحل نماذج الاختبار. مناسبة قبل الاختبارات الشهرية والنهائية." },
  // ---- تمور القصيم (طعام)
  { slug: "sukkari-dates-3kg", sub: "dates", seller: "dates_alqassim", kind: "product", category: "food", title: "تمر سكري فاخر ٣ كيلو", price: 95, photo: "dates,fruit,arabic", days: 4,
    desc: "سكري بريدة درجة أولى، رطب طري مبرّد، من محصول هذا الموسم. يوصل للرياض كل ثلاثاء وجمعة، والشحن للمدن الأخرى بالبريد المبرّد." },
  { slug: "majdool-box-1kg", sub: "dates", seller: "dates_alqassim", kind: "product", category: "food", title: "مجدول جامبو بعلبة هدية ١ كيلو", price: 70, photo: "medjool dates,box", days: 11,
    desc: "حبات كبيرة مرتبة في علبة أنيقة مناسبة للهدايا والضيافة. نضيف بطاقة إهداء مجاناً." },
  { slug: "dates-stuffed-nuts", sub: "dates", seller: "dates_alqassim", kind: "product", category: "food", title: "تمر محشي مكسرات ومغطى بالشوكولاتة ٥٠٠ غ", price: 85, photo: "chocolate dates,nuts", days: 7,
    desc: "خلاص محشي لوز وفستق وجوز، نصفه مغطى بشوكولاتة داكنة. يُحضّر بعد الطلب ليبقى طازجاً." },
  { slug: "dates-wholesale", sub: "dates", seller: "dates_alqassim", kind: "product", category: "food", title: "تمور بالجملة للمحلات والمطاعم (كرتون ١٠ كيلو)", price: 240, photo: "dates,market,boxes", days: 27,
    desc: "سكري أو خلاص أو صقعي، تعبئة كراتين ١٠ كيلو بسعر الجملة. الحد الأدنى ٥ كراتين، والتوصيل داخل الرياض مجاني." },
  // ---- لمى شموع (أعمال يدوية)
  { slug: "soy-candle-oud", sub: "candles", seller: "lama_candles", kind: "product", category: "handmade", title: "شمعة صويا برائحة العود والفانيلا ٢٢٠ غ", price: 65, photo: "candle,soy candle", days: 1,
    desc: "شمع صويا طبيعي وفتيل قطن، مدة احتراق ٤٠ ساعة. الرائحة تملأ الغرفة بدون دخان. متوفرة بروائح أخرى: ورد طائفي، لافندر، وقهوة." },
  { slug: "resin-tray-set", sub: "resin", seller: "lama_candles", kind: "product", category: "handmade", title: "صينية ريزن مع أكواب بورق ذهب", price: 240, photo: "resin art,tray", days: 8,
    desc: "صينية بيضاوية ٤٠ سم بريزن رخامي أبيض وذهبي مع ٤ كوستر. قطعة فريدة يدوية، مناسبة للضيافة والهدايا." },
  { slug: "wedding-favors-candles", sub: "candles", seller: "lama_candles", kind: "service", category: "handmade", title: "توزيعات أعراس: شموع صغيرة بالاسم (١٠٠ حبة)", price: 1400, photo: "wedding favors,candles", days: 14,
    desc: "شموع ٦٠ غ في أكواب زجاج مع غطاء وستيكر بأسماء العروسين وتاريخ الزواج. نجهّزها خلال ١٠ أيام، ونصمم الستيكر مجاناً." },
  { slug: "resin-keychains", sub: "resin", seller: "lama_candles", kind: "product", category: "handmade", title: "ميداليات ريزن بالحروف والورد المجفف", price: 25, photo: "resin keychain,flowers", days: 23,
    desc: "ميدالية شفافة بحرف الاسم وورد طبيعي مجفف. الطلب من ٥ حبات، وتناسب توزيعات المناسبات الصغيرة." },
  // ---- خالد تلميع (خدمات)
  { slug: "car-detailing-full", sub: "cars", seller: "khalid_detailing", kind: "service", category: "services", title: "تنظيف سيارة شامل داخلي وخارجي عند بيتك", price: 180, photo: "car detailing,car wash", days: 2,
    desc: "غسيل خارجي بالفوم، تنظيف الداخل بالبخار والمكينة، تلميع الجنوط والإطارات، وتعطير. مدة الخدمة ساعتان، وأنا أحضر بمعداتي ومائي." },
  { slug: "nano-ceramic-coating", sub: "cars", seller: "khalid_detailing", kind: "service", category: "services", title: "نانو سيراميك حماية ١٢ شهراً", price: 900, photo: "car polish,ceramic coating", days: 13,
    desc: "تلميع بمرحلتين لإزالة الخدوش الخفيفة ثم طبقة نانو سيراميك ٩H. لمعان وحماية من الشمس والغبار. يشمل الزجاج والجنوط." },
  { slug: "headlight-restore", sub: "cars", seller: "khalid_detailing", kind: "service", category: "services", title: "تجديد الشمعات (الإضاءة الأمامية)", price: 120, photo: "car headlight,polish", days: 24,
    desc: "إزالة الاصفرار والضبابية من الشمعات وإعادتها شفافة مع طبقة حماية. النتيجة خلال ٤٠ دقيقة." },
  // ---- ريم كيك (طعام)
  { slug: "birthday-cake-custom", sub: "sweets", seller: "reem_cakes", kind: "product", category: "food", title: "كيك عيد ميلاد بتصميم خاص (١٠ أشخاص)", price: 220, photo: "birthday cake,cake", days: 3,
    desc: "كيك فانيلا أو شوكولاتة أو ريد فيلفت بكريمة زبدة سويسرية، ونزيّنه بالثيم الذي تختاره. الطلب قبل ٤٨ ساعة والتوصيل داخل الخبر والدمام." },
  { slug: "cookies-box-24", sub: "sweets", seller: "reem_cakes", kind: "product", category: "food", title: "بوكس كوكيز مشكّل ٢٤ حبة", price: 95, photo: "cookies,chocolate chip", days: 6,
    desc: "شوكليت تشيب، لوتس، وبستاشيو محشي. كوكيز طرية من الداخل مقرمشة من الأطراف، تُخبز يوم التوصيل." },
  { slug: "brownies-tray", sub: "sweets", seller: "reem_cakes", kind: "product", category: "food", title: "صينية براونيز بالشوكولاتة البلجيكية", price: 80, photo: "brownies,chocolate", days: 15,
    desc: "١٦ قطعة براونيز فادج غنية بالشوكولاتة، مع خيار إضافة البندق أو الكراميل المملح. تكفي جلسة قهوة عائلية." },
  { slug: "cupcakes-dozen", sub: "sweets", seller: "reem_cakes", kind: "product", category: "food", title: "كب كيك مزيّن ١٢ حبة", price: 110, photo: "cupcakes,frosting", days: 20,
    desc: "كب كيك بنكهتين تختارهما، بتزيين يناسب مناسبتك (مواليد، تخرج، تجمّع). نغلّفها في علبة نافذة أنيقة." },
  // ---- أحمد صيانة (خدمات)
  { slug: "laptop-screen-replace", sub: "tech", seller: "ahmad_it_fix", kind: "service", category: "services", title: "تغيير شاشة لابتوب مع الضمان", price: 350, photo: "laptop repair,screen", days: 4,
    desc: "شاشات أصلية ومتوافقة لكل الماركات، تركيب خلال ساعة في المحل أو استلام وتوصيل داخل جدة. السعر يبدأ من ٣٥٠ حسب الموديل، مع ضمان ٦ أشهر." },
  { slug: "phone-battery-replace", sub: "tech", seller: "ahmad_it_fix", kind: "service", category: "services", title: "تغيير بطارية آيفون أو أندرويد", price: 130, photo: "phone repair,smartphone", days: 9,
    desc: "بطاريات بسعة كاملة مع تركيب خلال ٣٠ دقيقة، وفحص مجاني للشاحن والمنفذ. ضمان ٣ أشهر." },
  { slug: "data-recovery", sub: "tech", seller: "ahmad_it_fix", kind: "service", category: "services", title: "استرجاع بيانات من هارد أو جوال معطّل", price: 250, photo: "hard drive,data recovery", days: 17,
    desc: "فحص مجاني ثم سعر ثابت حسب الحالة. نسترجع الصور والملفات من الهاردات والجوالات المعطّلة، مع سرية تامة." },
  { slug: "laptop-upgrade-ssd", sub: "tech", seller: "ahmad_it_fix", kind: "service", category: "services", title: "ترقية لابتوب: SSD ورام وتنظيف", price: 280, photo: "ssd,computer parts", days: 26,
    desc: "تحويل النظام إلى SSD 512 غيغا (شامل القطعة)، زيادة الرام، تنظيف المراوح وتغيير المعجون الحراري. اللابتوب يرجع أسرع ٣ مرات." },
  // ---- سارة مكياج (خدمات)
  { slug: "bridal-makeup", sub: "beauty", seller: "sara_makeup", kind: "service", category: "services", title: "مكياج عروس في المنزل مع تجربة مسبقة", price: 1500, photo: "bridal makeup,bride", days: 5,
    desc: "جلسة تجربة قبل الزواج ثم مكياج يوم الزفاف في بيتك أو الفندق بمنتجات ثابتة ١٢ ساعة. يشمل الرموش وتثبيت الحجاب أو التسريحة البسيطة." },
  { slug: "henna-gulf-design", sub: "beauty", seller: "sara_makeup", kind: "service", category: "services", title: "نقش حناء خليجي لليدين", price: 150, photo: "henna,hands,mehndi", days: 3,
    desc: "حناء طبيعية بنقوش خليجية أو هندية للمناسبات والأعياد. اليدان فقط ١٥٠، مع القدمين ٢٥٠. الحد الأدنى للحضور المنزلي ٣ سيدات." },
  { slug: "makeup-course-basic", sub: "beauty", seller: "sara_makeup", kind: "service", category: "services", title: "كورس مكياج شخصي (جلستان)", price: 500, photo: "makeup,brushes,cosmetics", days: 19,
    desc: "تتعلمين تحضير البشرة، الكونتور المناسب لوجهك، والعيون السموكي. تحضرين أدواتك ونقيّمها معاً، وتحصلين على قائمة مقترحة." },
  // ---- تركي درون (تصوير)
  { slug: "real-estate-drone", sub: "drone", seller: "turki_drone", kind: "service", category: "photo", title: "تصوير عقار جوي وأرضي مع فيديو ٦٠ ثانية", price: 1200, photo: "drone,aerial,real estate", days: 2,
    desc: "لقطات جوية 4K للفلل والأراضي والمشاريع مع جولة أرضية وفيديو مونتاج بموسيقى وترخيص طيران ساري. مناسب لمكاتب العقار والمطورين." },
  { slug: "event-video-coverage", sub: "events", seller: "turki_drone", kind: "service", category: "photo", title: "تغطية فيديو لفعالية أو افتتاح (٤ ساعات)", price: 2500, photo: "videographer,event,camera", days: 10,
    desc: "كاميرتان وطيران درون، فيديو ملخص ٣ دقائق للسوشيال خلال ٢٤ ساعة، والملف الكامل خلال أسبوع." },
  { slug: "drone-farm-mapping", sub: "drone", seller: "turki_drone", kind: "service", category: "photo", title: "مسح جوي وخرائط للمزارع والأراضي", price: 1800, photo: "drone,farm,aerial view", days: 23,
    desc: "صور أورثو ونماذج ارتفاعات للأراضي حتى ٥٠ هكتاراً، بدقة تناسب التخطيط والتقسيم. التسليم بصيغ GeoTIFF وPDF." },
  // ---- عود الحرمين (هدايا)
  { slug: "cambodian-oud-tola", sub: "perfume", seller: "oud_alharamain", kind: "product", category: "gifts", title: "دهن عود كمبودي فاخر (تولة)", price: 650, photo: "oud,perfume bottle,arabic", days: 6,
    desc: "دهن عود معتّق ٨ سنوات برائحة حلوة عميقة. زجاجة تولة ١٢ مل في علبة مخملية، مناسب للإهداء في المناسبات الكبيرة." },
  { slug: "bakhoor-mix-100g", sub: "perfume", seller: "oud_alharamain", kind: "product", category: "gifts", title: "بخور معطّر خلطة المحل ١٠٠ غ", price: 120, photo: "incense,bakhoor,burner", days: 12,
    desc: "خلطة عود وصندل ومسك وعنبر تُطبخ في محلنا بالبلد. تكفي شهراً للاستخدام اليومي، وتأتي في علبة معدنية محكمة." },
  { slug: "oud-gift-set", sub: "perfume", seller: "oud_alharamain", kind: "product", category: "gifts", title: "طقم هدية: عود وبخور ومبخرة كهربائية", price: 380, photo: "gift set,incense burner", days: 16,
    desc: "قطع عود هندي ٢٠ غ، بخور معطّر ٥٠ غ، ومبخرة كهربائية محمولة، في صندوق خشب منقوش. التوصيل لكل المدن." },
  { slug: "oud-chips-indian-50g", sub: "perfume", seller: "oud_alharamain", kind: "product", category: "gifts", title: "عود هندي أسامي قطع ٥٠ غ", price: 420, photo: "agarwood,oud chips", days: 28,
    desc: "قطع عود هندي دهني بدخان كثيف وثبات طويل. مناسب للمجالس والضيافة، ونقدّم عينة ٥ غرام لمن يريد التجربة." },
  // ---- يارا فخار (أعمال يدوية)
  { slug: "ceramic-mug-set", sub: "pottery", seller: "yara_pottery", kind: "product", category: "handmade", title: "طقم أكواب سيراميك يدوي (٤ أكواب)", price: 260, photo: "ceramic mug,pottery", days: 2,
    desc: "أكواب ٣٠٠ مل مشغولة على العجلة وملوّنة بطلاء آمن غذائياً، كل كوب مختلف قليلاً كما تصنعه اليد. تدخل غسالة الصحون." },
  { slug: "pottery-workshop", sub: "pottery", seller: "yara_pottery", kind: "service", category: "handmade", title: "ورشة فخار للمبتدئين (ساعتان، قطعتان)", price: 220, photo: "pottery wheel,clay,hands", days: 7,
    desc: "تجرّب العجلة وتصنع كوباً وصحناً وتأخذهما بعد الحرق والتلوين خلال أسبوعين. للأفراد والمجموعات حتى ٦ أشخاص في مرسمي بالروضة." },
  { slug: "ceramic-vase-large", sub: "pottery", seller: "yara_pottery", kind: "product", category: "handmade", title: "مزهرية سيراميك كبيرة بلون الطين الطبيعي", price: 340, photo: "ceramic vase,pottery", days: 14,
    desc: "قطعة واحدة بارتفاع ٣٥ سم بتشطيب مطفي، مناسبة للورد المجفف والبامباس. أعمل مقاسات وألواناً خاصة بالطلب." },
  { slug: "ceramic-plates-cafe", sub: "pottery", seller: "yara_pottery", kind: "service", category: "handmade", title: "أطقم صحون وأكواب مخصصة للمقاهي (طلب من ٢٤ قطعة)", price: 55, photo: "ceramic plates,cafe", days: 21,
    desc: "السعر للقطعة، مع ختم شعار مقهاك على القاعدة وألوان تناسب هويتك. مدة التنفيذ ٤ أسابيع." },
  // ---- فهد نقل (توصيل)
  { slug: "furniture-moving-dyna", sub: "moving", seller: "fahad_moving", kind: "service", category: "delivery", title: "دينا نقل أثاث داخل جدة مع عاملين", price: 350, photo: "moving truck,furniture", days: 1,
    desc: "نقل شقة صغيرة أو مكتب في نقلة واحدة، مع عاملين للتحميل والتنزيل. الفك والتركيب ١٥٠ إضافية، والتغليف بالبلاستيك والكرتون متوفر." },
  { slug: "single-item-transport", sub: "moving", seller: "fahad_moving", kind: "service", category: "delivery", title: "نقل قطعة واحدة (ثلاجة، غسالة، كنب)", price: 120, photo: "delivery,appliance,truck", days: 8,
    desc: "استلام من المعرض أو البيت وتوصيل لأي حي في جدة مع الرفع للدور. مناسب لمشتريات حراج والمعارض." },
  { slug: "jeddah-makkah-moving", sub: "moving", seller: "fahad_moving", kind: "service", category: "delivery", title: "نقل عفش من جدة إلى مكة أو الطائف", price: 900, photo: "moving,boxes,truck", days: 18,
    desc: "دينا مغلقة مع ٣ عمّال، فك وتركيب غرف النوم مشمول. نتفق على الموعد ونلتزم به، والتغليف الكامل بسعر إضافي." },
  // ---- أمل عربي (خدمات)
  { slug: "quran-memorization-kids", sub: "education", seller: "amal_arabic", kind: "service", category: "services", title: "تحفيظ قرآن للأطفال (٨ حصص شهرياً)", price: 400, photo: "quran,reading,book", days: 3,
    desc: "حلقة صغيرة أو فردي، حصتان أسبوعياً بمدة ٤٥ دقيقة، مع متابعة المراجعة عبر الواتساب. حضوري في شمال الرياض أو عبر زوم." },
  { slug: "arabic-for-non-native", sub: "education", seller: "amal_arabic", kind: "service", category: "services", title: "عربي لغير الناطقين بها، محادثة وقراءة", price: 120, photo: "arabic calligraphy,learning", days: 11,
    desc: "درس ساعة للكبار والأطفال، منهج مبني على المواقف اليومية والعمل. الدرس الأول تجريبي بنصف السعر." },
  { slug: "tajweed-adults", sub: "education", seller: "amal_arabic", kind: "service", category: "services", title: "تصحيح تلاوة وتجويد للكبار", price: 100, photo: "quran,mosque,prayer", days: 25,
    desc: "جلسة ساعة أسبوعياً لتصحيح مخارج الحروف وأحكام التجويد بإجازة متصلة، للنساء فقط، أونلاين أو حضوري." },
  // ---- نواف قهوة (قهوة)
  { slug: "v60-starter-kit", sub: "tools", seller: "coffee_corner_dmm", kind: "product", category: "coffee", title: "طقم V60 للمبتدئين: دريبر وسيرفر وفلاتر وميزان", price: 240, photo: "v60,pour over,coffee kit", days: 2,
    desc: "دريبر سيراميك مقاس ٠٢، سيرفر زجاج ٦٠٠ مل، ١٠٠ فلتر، وميزان رقمي بمؤقت. أرفق ورقة نسب مطبوعة وشرحاً بالفيديو." },
  { slug: "hand-grinder-steel", sub: "tools", seller: "coffee_corner_dmm", kind: "product", category: "coffee", title: "مطحنة يدوية بشفرات ستيل مخروطية", price: 320, photo: "coffee grinder,manual", days: 9,
    desc: "طحن ثابت للإسبريسو والفلتر بضبط ٤٠ درجة، جسم ألمنيوم يتحمل السفر. مناسبة للرحلات والكشتات." },
  { slug: "chemex-6cup", sub: "tools", seller: "coffee_corner_dmm", kind: "product", category: "coffee", title: "كيمكس ٦ أكواب مع ١٠٠ فلتر", price: 260, photo: "chemex,coffee,glass", days: 15,
    desc: "زجاج بوروسيليكات أصلي بحزام خشب، للقهوة الصافية النظيفة. الفلاتر السميكة الأصلية مرفقة." },
  { slug: "local-roaster-sampler", sub: "beans", seller: "coffee_corner_dmm", kind: "product", category: "coffee", title: "بوكس تذوق: ٤ محامص سعودية × ١٠٠ غ", price: 130, photo: "coffee sampler,beans,bags", days: 5,
    desc: "أربع محاصيل مختارة من محامص في الدمام والرياض وجدة، تحميص فاتح للفلتر. تجربة ممتازة قبل أن تشتري الكيلو." },
  // ---- حصة عبايات (أخرى)
  { slug: "abaya-custom-korean", sub: "clothing", seller: "hessa_abayas", kind: "product", category: "other", title: "عباية كوري على المقاس بتصميمك", price: 380, photo: "abaya,fabric,sewing", days: 4,
    desc: "تختارين القماش والموديل من كتالوجنا أو صورة، والقياس في المشغل بالسلامة أو تُرسلينه. التسليم خلال ١٠ أيام مع تعديل مجاني." },
  { slug: "jalabiya-eid", sub: "clothing", seller: "hessa_abayas", kind: "product", category: "other", title: "جلابية بيتية مطرزة، مقاسات حتى XXL", price: 220, photo: "kaftan,embroidery,dress", days: 12,
    desc: "قماش قطن مريح بتطريز يدوي على الصدر والأكمام، ألوان متعددة. متوفرة جاهزة، ونفصّل مقاسات خاصة." },
  { slug: "abaya-alteration", sub: "tailoring", seller: "hessa_abayas", kind: "service", category: "other", title: "تعديل وتضييق عبايات وفساتين", price: 60, photo: "tailor,sewing machine", days: 20,
    desc: "تقصير، تضييق، تغيير سحّاب، وإصلاح تطريز. السعر يبدأ من ٦٠ حسب التعديل، والتسليم خلال ٣ أيام." },
  // ---- عمر نباتات (أخرى)
  { slug: "monstera-large", sub: "plants", seller: "omar_plants", kind: "product", category: "other", title: "مونستيرا كبيرة ١٢٠ سم في حوض فخار", price: 280, photo: "monstera,plant,indoor", days: 2,
    desc: "نبتة صحية من مشتلي بأوراق مثقوبة كاملة، مع حوض فخار ٣٠ سم وتربة مناسبة. تحب الإضاءة غير المباشرة وريّة أسبوعية." },
  { slug: "office-plants-package", sub: "plants", seller: "omar_plants", kind: "service", category: "other", title: "تخضير مكتب: ١٠ نباتات مع عناية شهرية", price: 1500, photo: "office plants,green,indoor", days: 9,
    desc: "نختار النباتات المناسبة لإضاءة مكتبكم، ونزورها مرتين شهرياً للري والتسميد والاستبدال إن ذبلت. السعر للثلاثة أشهر الأولى." },
  { slug: "succulent-set-5", sub: "plants", seller: "omar_plants", kind: "product", category: "other", title: "طقم صبّار وعصاريات ٥ نباتات بأحواض", price: 95, photo: "succulents,cactus,pots", days: 16,
    desc: "خمسة أنواع مختلفة في أحواض سيراميك صغيرة، تحتاج ريّة كل أسبوعين وشمس. هدية جميلة للمكاتب وطاولات الدراسة." },
  { slug: "garden-consult", sub: "plants", seller: "omar_plants", kind: "service", category: "other", title: "استشارة تنسيق حديقة منزلية (زيارة ساعة)", price: 200, photo: "garden,landscaping,plants", days: 24,
    desc: "أزور حديقتك وأقترح النباتات المناسبة للشمس والتربة والري بالتنقيط، مع مخطط مبسّط وقائمة شراء بالأسعار." },
  // ---- بسام تصميم (خدمات)
  { slug: "logo-brand-identity", sub: "design", seller: "bassam_design", kind: "service", category: "services", title: "شعار وهوية بصرية كاملة لمشروعك", price: 2500, photo: "logo design,branding,designer", days: 1,
    desc: "٣ مقترحات شعار، دليل هوية بالألوان والخطوط، وتطبيقات (بطاقة، ورق رسمي، أيقونة تطبيق، غلاف سوشيال). تسليم الملفات المفتوحة خلال ١٠ أيام." },
  { slug: "restaurant-menu-design", sub: "design", seller: "bassam_design", kind: "service", category: "services", title: "تصميم منيو مطعم أو مقهى (مطبوع ورقمي)", price: 700, photo: "menu design,restaurant", days: 7,
    desc: "منيو أنيق بصور منتجاتك أو أيقونات، نسخة للطباعة ونسخة QR للجوال. يشمل جولتي تعديل." },
  { slug: "social-media-month", sub: "design", seller: "bassam_design", kind: "service", category: "services", title: "إدارة سوشيال ميديا شهرية (٢٠ منشوراً)", price: 1800, photo: "social media,smartphone,content", days: 13,
    desc: "تصميم وكتابة ٢٠ منشوراً وستوري لإنستقرام وتيك توك مع جدولة النشر وتقرير أداء شهري. لا يشمل الإعلانات المدفوعة." },
  { slug: "video-editing-reel", sub: "design", seller: "bassam_design", kind: "service", category: "services", title: "مونتاج ريلز وتيك توك (٥ فيديوهات)", price: 450, photo: "video editing,timeline", days: 22,
    desc: "قص وتلوين وترجمة وموسيقى مرخّصة لفيديوهاتك القصيرة. ترسل المقاطع الخام وتستلم النسخ خلال ٣ أيام." },
  // ---- غادة ورد (هدايا)
  { slug: "rose-bouquet-25", sub: "flowers", seller: "ghada_flowers", kind: "product", category: "gifts", title: "باقة ٢٥ وردة جوري أحمر", price: 220, photo: "roses,bouquet,red", days: 1,
    desc: "ورد هولندي طازج بتغليف كرافت وشريط ساتان وبطاقة بخط اليد. التوصيل داخل الخبر والدمام خلال ٣ ساعات." },
  { slug: "flower-box-mixed", sub: "flowers", seller: "ghada_flowers", kind: "product", category: "gifts", title: "بوكس ورد مشكّل مع شوكولاتة", price: 290, photo: "flower box,chocolate", days: 6,
    desc: "بوكس مربّع أسود بورد جوري وليليوم وأوكالبتوس، مع علبة شوكولاتة باتشي ٢٥٠ غ. مناسب للتخرج والمواليد." },
  { slug: "wedding-table-flowers", sub: "flowers", seller: "ghada_flowers", kind: "service", category: "gifts", title: "تنسيق ورد لطاولات المناسبات (١٠ طاولات)", price: 2200, photo: "wedding flowers,table decor", days: 14,
    desc: "تنسيق مركزي لكل طاولة بورد طبيعي بألوان الحفل، مع طاولة الكوشة بسعر منفصل. نزور الموقع قبل الحفل بيوم." },
  { slug: "dried-flowers-vase", sub: "flowers", seller: "ghada_flowers", kind: "product", category: "gifts", title: "تنسيق ورد مجفف بمزهرية زجاج", price: 160, photo: "dried flowers,vase,pampas", days: 19,
    desc: "بامباس ولافندر وقطن مجفف في مزهرية زجاج طويلة، يدوم سنة بلا عناية. ألوان طبيعية وبيج وردي." },
  // ---- علي مدرب (خدمات)
  { slug: "personal-training-12", sub: "fitness", seller: "coach_ali_fit", kind: "service", category: "services", title: "تدريب شخصي ١٢ جلسة في النادي أو البيت", price: 1500, photo: "personal trainer,gym,fitness", days: 2,
    desc: "برنامج مصمم لهدفك (نزول وزن أو بناء عضل) مع قياسات كل أسبوعين وخطة تغذية مرنة. الجلسة ساعة، للرجال في الدمام والخبر." },
  { slug: "nutrition-plan", sub: "fitness", seller: "coach_ali_fit", kind: "service", category: "services", title: "خطة تغذية شهرية مع متابعة أسبوعية", price: 350, photo: "healthy food,meal plan", days: 10,
    desc: "خطة أكل من أطباقنا المحلية بسعرات محسوبة، ومتابعة أسبوعية بالواتساب لتعديلها حسب تقدمك. لا مكملات إلزامية." },
  { slug: "group-bootcamp", sub: "fitness", seller: "coach_ali_fit", kind: "service", category: "services", title: "بوت كامب صباحي على كورنيش الدمام (شهر)", price: 400, photo: "bootcamp,outdoor workout", days: 17,
    desc: "٣ أيام أسبوعياً الساعة ٦ صباحاً، تمارين وزن الجسم وجري خفيف، مجموعات حتى ١٠ أشخاص. أول حصة مجانية." },
  // ---- دانة إنجليزي (خدمات)
  { slug: "ielts-prep-course", sub: "education", seller: "english_with_dana", kind: "service", category: "services", title: "دورة تحضير آيلتس (١٦ ساعة أونلاين)", price: 1200, photo: "english class,online learning", days: 3,
    desc: "استراتيجيات الأقسام الأربعة مع اختبارات محاكية وتصحيح كتابة فردي. متوسط تحسّن طلابي درجة كاملة. مجموعات حتى ٦." },
  { slug: "english-conversation", sub: "education", seller: "english_with_dana", kind: "service", category: "services", title: "محادثة إنجليزي للموظفين (٨ جلسات)", price: 640, photo: "conversation,coffee,talking", days: 8,
    desc: "جلسات مسائية عبر زوم، ٦٠ دقيقة، بمواقف العمل: اجتماعات، إيميلات، عروض تقديمية. تقييم مستوى مجاني قبل البدء." },
  { slug: "kids-english-club", sub: "education", seller: "english_with_dana", kind: "service", category: "services", title: "نادي إنجليزي للأطفال ٦ إلى ١٠ سنوات (شهرياً)", price: 450, photo: "kids learning,classroom", days: 21,
    desc: "حصتان أسبوعياً حضورياً في الربيع، تعلّم بالقصص والألعاب والأغاني، مجموعات صغيرة حتى ٨ أطفال." },
  // ---- ثامر كتب (أخرى)
  { slug: "novels-bundle-10", sub: "books", seller: "books_jeddah", kind: "product", category: "other", title: "١٠ روايات عربية مترجمة بحالة ممتازة", price: 150, photo: "books,novels,bookshelf", days: 2,
    desc: "مجموعة مختارة: ساراماغو، إيزابيل الليندي، أورهان باموق وغيرهم. الكتب نظيفة بلا كتابة، وأرسل قائمتها بالصور." },
  { slug: "university-textbooks", sub: "books", seller: "books_jeddah", kind: "product", category: "other", title: "كتب جامعية: هندسة وحاسب (سعر القطعة)", price: 40, photo: "textbooks,university,study", days: 12,
    desc: "كتب مقررات جامعة الملك عبدالعزيز والملك فهد بطبعات حديثة. أرسل اسم المقرر وأخبرك بالمتوفر، والاستلام في الأندلس." },
  { slug: "book-exchange", sub: "books", seller: "books_jeddah", kind: "service", category: "other", title: "مبادلة كتب: كتابك مقابل كتاب من رفوفي", price: 10, photo: "used books,reading", days: 27,
    desc: "تجيب كتاباً بحالة جيدة وتأخذ آخر من ٣٠٠ عنوان، برسوم رمزية ١٠ ريالات. أنظّم جلسة مبادلة كل جمعة مساءً." },
  // ---- إضافات متنوعة في تصنيفات أقل
  { slug: "home-nurse-visit", sub: "cleaning", seller: "abu_saud_ac", kind: "service", category: "services", title: "غسيل خزانات المياه وتعقيمها", price: 250, photo: "water tank,cleaning", days: 29,
    desc: "تفريغ الخزان العلوي أو الأرضي، إزالة الرواسب، التعقيم بالكلور المعتمد، وإعادة التعبئة. مرة كل ٦ أشهر تحفظ صحة أهل البيت." },
  { slug: "cake-pops-30", sub: "sweets", seller: "reem_cakes", kind: "product", category: "food", title: "كيك بوبس للتوزيعات ٣٠ حبة", price: 120, photo: "cake pops,sweets", days: 28,
    desc: "كيك بوبس مغلفة فردياً بألوان مناسبتك مع ستيكر اسم، مثالية لتوزيعات المدارس والمواليد." },
  { slug: "wedding-invite-photo", sub: "events", seller: "lens_rayan", kind: "service", category: "photo", title: "تصوير دعوة زواج فيديو قصير", price: 800, photo: "wedding invitation,video", days: 29,
    desc: "فيديو دعوة ٣٠ ثانية بأسماء العروسين والموعد والموقع، بلقطات من جدة أو موشن جرافيك، جاهز للواتساب." },
  { slug: "gift-wrapping-service", sub: "boxes", seller: "hind_gifts", kind: "service", category: "gifts", title: "تغليف هداياك الجاهزة بشكل احترافي", price: 35, photo: "gift wrapping,paper,bow", days: 26,
    desc: "تحضر هديتك ونغلّفها بورق وشرائط وبطاقة تناسب المناسبة. السعر للقطعة الواحدة، وتوصيل داخل الرياض بـ ٢٠ ريالاً." },
  { slug: "carpet-cleaning", sub: "cleaning", seller: "khalid_detailing", kind: "service", category: "services", title: "غسيل سجاد وكنب بالبخار في المنزل", price: 200, photo: "carpet cleaning,steam", days: 30,
    desc: "تنظيف عميق بالبخار وشفط الماء، يزيل البقع والروائح ويجفّ خلال ساعات. السعر للمجلس الواحد حتى ٨ مقاعد." },
  { slug: "pastry-basket-ramadan", sub: "pastries", seller: "um_fahad_kitchen", kind: "product", category: "food", title: "سلة معجنات مشكّلة (٤٠ قطعة)", price: 110, photo: "pastries,bakery,basket", days: 24,
    desc: "فطاير جبن وزعتر ولحم بعجين وبيتزا صغيرة، تُخبز يوم التوصيل وتوصل دافئة. مناسبة للاجتماعات والمجالس." },
  { slug: "drone-wedding-outdoor", sub: "drone", seller: "turki_drone", kind: "service", category: "photo", title: "لقطات درون لحفل خارجي أو استراحة", price: 700, photo: "drone,sunset,aerial", days: 27,
    desc: "ساعة تصوير جوي لحفلات الاستراحات والمزارع بالرياض، تسليم ١٠ لقطات معدّلة وفيديو ٤٥ ثانية خلال ٤٨ ساعة." },
  { slug: "resin-clock", sub: "resin", seller: "lama_candles", kind: "product", category: "handmade", title: "ساعة حائط ريزن ٤٠ سم بورق ذهب", price: 320, photo: "resin clock,wall clock", days: 29,
    desc: "قرص ريزن بتدرجات تختارها، ماكينة صامتة وأرقام معدنية. قطعة فنية تناسب المجالس والمكاتب." },
  { slug: "pottery-kids-party", sub: "pottery", seller: "yara_pottery", kind: "service", category: "handmade", title: "حفلة فخار للأطفال (١٠ أطفال، ساعتان)", price: 900, photo: "kids pottery,clay,painting", days: 28,
    desc: "نشاط تلوين وتشكيل طين في مرسمي أو في مكانك بالرياض، كل طفل يرجع بقطعته بعد الحرق. يشمل المرايل والأدوات." },
  { slug: "khobar-flowers-subscription", sub: "flowers", seller: "ghada_flowers", kind: "service", category: "gifts", title: "اشتراك باقة ورد أسبوعية للمكتب أو البيت", price: 480, photo: "flowers,vase,fresh", days: 23,
    desc: "باقة طازجة موسمية كل أحد لمدة شهر، مع مزهرية في أول توصيلة. الإلغاء في أي وقت." },
  { slug: "dates-coffee-gift", sub: "boxes", seller: "dates_alqassim", kind: "product", category: "gifts", title: "صندوق ضيافة: تمر سكري وقهوة سعودية", price: 140, photo: "dates,arabic coffee,gift", days: 18,
    desc: "كيلو سكري فاخر و٢٥٠ غ قهوة سعودية مطحونة في صندوق خشب بشعار محفور. هدية مثالية للضيوف والشركاء." },
  { slug: "pet-transport", sub: "pets", seller: "wasel_express", kind: "service", category: "delivery", title: "توصيل قطط وحيوانات أليفة للبيطري", price: 60, photo: "cat carrier,pet", days: 25,
    desc: "أستلم قطتك في بوكسها وأوصلها للعيادة وأرجعها، مع تكييف السيارة طوال الطريق. داخل جدة فقط." },
  { slug: "laptop-cleaning", sub: "tech", seller: "ahmad_it_fix", kind: "service", category: "services", title: "تنظيف داخلي للابتوب وتغيير المعجون الحراري", price: 90, photo: "laptop,cleaning,dust", days: 30,
    desc: "يقلل الحرارة وصوت المروحة ويرجّع الأداء. مدة الخدمة ساعة في المحل بالفيصلية." },
];
