// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuiBhb4-B_XpQ87hWFV7c7bsAgGLPGKx8',
    appId: '1:560826039000:web:a983cbf1e9472dcbbe75ad',
    messagingSenderId: '560826039000',
    projectId: 'naslook-c10ec',
    authDomain: 'naslook-c10ec.firebaseapp.com',
    storageBucket: 'naslook-c10ec.firebasestorage.app',
    measurementId: 'G-KHQVZNHKN1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGdXwDRIfr941_yfxu3bpNg1TKYhPnbj0',
    appId: '1:560826039000:android:c714f2331a18dc4cbe75ad',
    messagingSenderId: '560826039000',
    projectId: 'naslook-c10ec',
    storageBucket: 'naslook-c10ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApTadZlET6EeD9tAM8vuakEBcAq_hbnJ8',
    appId: '1:560826039000:ios:e9738d993c70229abe75ad',
    messagingSenderId: '560826039000',
    projectId: 'naslook-c10ec',
    storageBucket: 'naslook-c10ec.firebasestorage.app',
    iosBundleId: 'com.example.naslook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuiBhb4-B_XpQ87hWFV7c7bsAgGLPGKx8',
    appId: '1:560826039000:web:bb23caca243a663abe75ad',
    messagingSenderId: '560826039000',
    projectId: 'naslook-c10ec',
    authDomain: 'naslook-c10ec.firebaseapp.com',
    storageBucket: 'naslook-c10ec.firebasestorage.app',
    measurementId: 'G-7HLQ47BWM3',
  );
}