// اختبارات روابط المشاركة (server/share.js): /c/<دائرة> و /u/<نك نيم> يقدّمان index.html مع وسوم Open Graph صحيحة،
// ووسوم عامة للمجهول أو الخاص، وتهريب HTML.
import Fastify from 'fastify';
import pg from 'pg';
process.env.NASLIFE_HEALTH_BRIDGE = '0';
const dir = new URL('.', import.meta.url).pathname;
const pool = new pg.Pool({ host: '127.0.0.1', user: 'postgres', password: 'pg', database: 'naslife_test' });
await pool.query("CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, nickname TEXT, avatar_url TEXT, is_admin BOOLEAN DEFAULT false, created_at TIMESTAMPTZ DEFAULT now())");
await pool.query("INSERT INTO users(id,nickname,avatar_url) VALUES('SA0000001','amr','/files/amr.jpg'),('SA0000002','sara',NULL) ON CONFLICT (id) DO UPDATE SET avatar_url=EXCLUDED.avatar_url");
await pool.query("CREATE TABLE IF NOT EXISTS profiles (user_id TEXT PRIMARY KEY, bio TEXT, is_public BOOLEAN DEFAULT true)");
await pool.query("INSERT INTO profiles(user_id,bio,is_public) VALUES('SA0000001','أحب القهوة <b>والبحر</b>',true),('SA0000002','سرّي',false) ON CONFLICT (user_id) DO UPDATE SET bio=EXCLUDED.bio, is_public=EXCLUDED.is_public");
const auth = async (req) => req.headers['x-user'] || null;
const app = Fastify();
app.register((await import('../business.js')).default, { pool, auth });
app.register((await import('../share.js')).default, { pool, auth, webappDir: dir + 'webapp' });
await app.ready(); await new Promise((r) => setTimeout(r, 800));
let fails = 0;
const check = (cond, label, extra = '') => { if (!cond) fails++; console.log((cond ? 'OK  ' : 'FAIL') + ' ' + label + (extra ? ' ' + extra : '')); };
const get = async (url) => { const r = await app.inject({ method: 'GET', url, headers: { host: 'www.naslife.app', 'x-forwarded-proto': 'https' } }); return { code: r.statusCode, type: r.headers['content-type'], body: r.body }; };
const meta = (html, prop) => (html.match(new RegExp(`<meta (?:property|name)="${prop}" content="([^"]*)"`)) || [])[1];
const st = await get('/share/status');
check(st.code === 200 && JSON.parse(st.body).avatarColumn === 'avatar_url' && JSON.parse(st.body).privacy === true, 'status discovers avatar column and privacy', st.body);
let r = await get('/c/biz-brew92');
check(r.code === 200 && /text\/html/.test(r.type) && r.body.includes('<div id="app">'), 'circle link serves the web app');
check(meta(r.body, 'og:title') === 'برو 92 · ناس لايف' && meta(r.body, 'og:image') === 'https://naslife.app/assets/assets/biz/brew92.png' && meta(r.body, 'og:url') === 'https://naslife.app/c/biz-brew92', 'circle OG title/image/url (www stripped, asset logo)', JSON.stringify({ t: meta(r.body, 'og:title'), i: meta(r.body, 'og:image'), u: meta(r.body, 'og:url') }));
check(r.body.includes('<title>برو 92 · ناس لايف</title>') && !r.body.includes('<title>Naslife</title>'), 'title replaced');
check((meta(r.body, 'og:description') || '').includes('محامص'), 'circle description from seed');
r = await get('/c/biz-cuprover');
check(r.code === 200 && meta(r.body, 'og:image') === undefined && meta(r.body, 'og:title') === 'كب روفر · ناس لايف', 'circle without logo has no og:image');
r = await get('/c/nope-nope');
check(r.code === 200 && meta(r.body, 'og:title') === 'دائرة على Naslife · ناس لايف', 'unknown circle still serves the app with generic tags');
r = await get('/c/..%2F..%2Fetc');
check(r.code === 200 && (meta(r.body, 'og:title') || '').startsWith('دائرة على'), 'bad id is safe');
r = await get('/u/AMR');
check(r.code === 200 && meta(r.body, 'og:title') === 'amr · ناس لايف' && meta(r.body, 'og:description') === 'أحب القهوة &lt;b&gt;والبحر&lt;/b&gt;' && meta(r.body, 'og:image') === 'https://naslife.app/files/amr.jpg' && meta(r.body, 'og:type') === 'profile', 'profile link: case-insensitive nickname, escaped bio, avatar', JSON.stringify({ t: meta(r.body, 'og:title'), d: meta(r.body, 'og:description'), i: meta(r.body, 'og:image') }));
r = await get('/u/sara');
check(r.code === 200 && meta(r.body, 'og:title') === 'sara · ناس لايف' && meta(r.body, 'og:image') === undefined && !r.body.includes('سرّي'), 'private profile: no bio, no image');
r = await get('/u/nobody_here');
check(r.code === 200 && meta(r.body, 'og:title') === 'حساب على Naslife · ناس لايف', 'unknown nickname: generic tags');
r = await get('/u/%3Cscript%3E');
check(r.code === 200 && !r.body.includes('<script>'), 'nickname is escaped');
await pool.query("DROP TABLE IF EXISTS profiles");
await app.close(); await pool.end();
console.log(fails ? `\n${fails} FAILED` : '\nALL SHARE TESTS PASSED');
process.exit(fails ? 1 : 0);
