// الحسابات بالبريد (server/auth_alias.js): تمهيد البريد من المستودع، الدخول بالبريد، تعيين/تأكيد البريد بالرمز،
// التسجيل بالبريد مع حفظ عبارة الاسترداد مشفّرة، نسيت كلمة السر (رمز بالبريد ← /recover في النواة)، تغيير كلمة السر،
// وتفعيل الاستعادة للحسابات القديمة بعبارتها. النواة وهمية: /register و/login و/recover بعبارة تتغير وجلسات تُلغى.
import Fastify from 'fastify';
import pg from 'pg';
import fs from 'node:fs';
import { startFakeSmtp, plainTextOf } from './fake_smtp.mjs';
process.env.NASLIFE_HEALTH_BRIDGE = '0';
const OPS = new URL('./ops-test', import.meta.url).pathname;
fs.rmSync(OPS, { recursive: true, force: true });
const pool = new pg.Pool({ host: '127.0.0.1', user: 'postgres', password: 'pg', database: 'naslife_test' });
await pool.query("CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, nickname TEXT, avatar_url TEXT, is_admin BOOLEAN DEFAULT false, created_at TIMESTAMPTZ DEFAULT now())");
await pool.query("DELETE FROM users WHERE id NOT IN ('SA9954961','SA0000002')");
await pool.query("INSERT INTO users(id,nickname) VALUES('SA9954961','jeddahh'),('SA0000002','sara') ON CONFLICT (id) DO UPDATE SET nickname=EXCLUDED.nickname");
await pool.query("DROP TABLE IF EXISTS login_aliases; DROP TABLE IF EXISTS account_recovery; DROP TABLE IF EXISTS mail_settings; DROP TABLE IF EXISTS mail_log");
globalThis.naslifeIsAdmin = async (uid) => uid === 'SA9954961';
delete globalThis.naslifeMail;
const smtp = await startFakeSmtp({ user: 'mailer', pass: 'secret' });
const app = Fastify();
// ---- نواة وهمية: حسابات في الذاكرة بكلمة سر وعبارة استرداد وجلسات
const accounts = { jeddahh: { id: 'SA9954961', password: 'TestPass#2026', phrase: 'حلوى موج فندق شكل كمان بطاطس' }, sara: { id: 'SA0000002', password: 'secret', phrase: 'a b c d e f' } };
const sessions = new Map(); let seq = 10; let phraseSeq = 0;
const issue = (nick) => { for (const [t, n] of sessions) if (n === nick) sessions.delete(t); const t = 'tok-' + nick + '-' + (++seq); sessions.set(t, nick); return t; };
const newPhrase = () => 'عبارة جديدة رقم ' + (++phraseSeq) + ' كلمات ست';
app.post('/register', async (req, reply) => { const { nickname, password } = req.body ?? {}; if (!/^[a-z0-9_]{3,32}$/.test(nickname ?? '')) return reply.code(400).send({ error: 'invalid-nickname' }); if (accounts[nickname]) return reply.code(409).send({ error: 'nickname-taken' }); if (String(password ?? '').length < 8) return reply.code(400).send({ error: 'weak-password' }); const id = 'SA00000' + (++seq); accounts[nickname] = { id, password, phrase: newPhrase() }; await pool.query('INSERT INTO users(id,nickname) VALUES($1,$2)', [id, nickname]); return { id, nickname, token: issue(nickname), recoveryPhrase: accounts[nickname].phrase, hasRecovery: true }; });
app.post('/login', async (req, reply) => { const { handle, password } = req.body ?? {}; const a = accounts[handle]; if (a && a.password === password) return { id: a.id, nickname: handle, token: issue(handle) }; return reply.code(401).send({ error: 'bad-credentials' }); });
app.post('/logout', async (req) => { sessions.delete(req.headers['x-token']); return { ok: true }; });
app.post('/recover', async (req, reply) => { const { handle, recoveryPhrase, newPassword } = req.body ?? {}; const a = accounts[handle]; if (!a || a.phrase !== recoveryPhrase) return reply.code(401).send({ error: 'bad-code' }); if (String(newPassword ?? '').length < 8) return reply.code(400).send({ error: 'weak-password' }); a.password = newPassword; a.phrase = newPhrase(); return { id: a.id, nickname: handle, token: issue(handle), recoveryPhrase: a.phrase, hasRecovery: true }; });
const auth = async (req) => { const h = req.headers['x-user']; if (h) return h; const t = req.headers['x-token']; const n = t && sessions.get(t); return n ? accounts[n].id : null; };
app.register((await import('../auth_alias.js')).default, { pool, auth, opsDir: OPS });
app.register((await import('../mail.js')).default, { pool, auth });
await app.ready();
let fails = 0;
const check = (c, l, extra = '') => { if (!c) fails++; console.log((c ? 'OK  ' : 'FAIL') + ' ' + l + (extra ? ' ' + extra : '')); };
const call = async (method, url, { body, user, token } = {}) => { const r = await app.inject({ method, url, headers: { 'content-type': 'application/json', ...(user ? { 'x-user': user } : {}), ...(token ? { 'x-token': token } : {}) }, payload: body ? JSON.stringify(body) : undefined }); let j; try { j = r.json(); } catch { j = r.body; } return { code: r.statusCode, json: j }; };
const SARA = { user: 'SA0000002' }, ADMIN = { user: 'SA9954961' };
const codeOf = (i) => (plainTextOf(smtp.messages[i].raw).match(/\b(\d{6})\b/) || [])[1];

let r = await call('GET', '/auth/alias/status');
check(r.code === 200 && r.json.aliases === 1 && r.json.verified === 1 && r.json.recoverable === 0 && r.json.mailConfigured === false, 'bootstrap alias seeded as verified; nothing recoverable; mail off', JSON.stringify(r.json));
check(fs.existsSync(OPS + '/auth-key') && /^[0-9a-f]{64}\n?$/.test(fs.readFileSync(OPS + '/auth-key', 'utf8')), 'auth-key generated in ops dir with 32 random bytes');
r = await call('POST', '/auth/login', { body: { handle: 'Jeddahh@Gmail.com', password: 'TestPass#2026' } });
check(r.code === 200 && r.json.token?.startsWith('tok-jeddahh') && r.json.id === 'SA9954961', 'login with email (any case) returns the core session');
r = await call('POST', '/auth/login', { body: { handle: 'jeddahh@gmail.com', password: 'wrong' } });
check(r.code === 401 && r.json.error === 'bad-credentials', 'wrong password rejected by the core');
r = await call('POST', '/auth/login', { body: { handle: 'nobody@example.com', password: 'x' } });
check(r.code === 401 && r.json.error === 'bad-credentials', 'unknown email rejected without enumeration');
r = await call('POST', '/auth/login', { body: { handle: 'sara', password: 'secret' } });
check(r.code === 200 && r.json.token?.startsWith('tok-sara'), 'nickname login passes through');
// ---- التسجيل بالبريد
r = await call('POST', '/auth/register', { body: { email: 'bad', nickname: 'newuser', password: 'Password1' } });
check(r.code === 400 && r.json.error === 'bad-email', 'register: bad email');
r = await call('POST', '/auth/register', { body: { email: 'new@example.com', nickname: 'New User', password: 'Password1' } });
check(r.code === 400 && r.json.error === 'invalid-nickname', 'register: invalid nickname');
r = await call('POST', '/auth/register', { body: { email: 'new@example.com', nickname: 'a'.repeat(26), password: 'Password1' } });
check(r.code === 400 && r.json.error === 'invalid-nickname', 'register: nickname longer than 25 rejected');
r = await call('GET', '/auth/nickname-available?nickname=Sara');
check(r.code === 200 && r.json.available === false && r.json.reason === 'taken', 'nickname-available: taken (case-insensitive)');
r = await call('GET', '/auth/nickname-available?nickname=free_name_2026');
check(r.code === 200 && r.json.available === true, 'nickname-available: free');
r = await call('GET', '/auth/nickname-available?nickname=ab');
check(r.code === 200 && r.json.available === false && r.json.reason === 'invalid', 'nickname-available: invalid format');
r = await call('GET', '/auth/nickname-available?nickname=' + 'b'.repeat(25));
check(r.code === 200 && r.json.available === true, 'nickname-available: 25 chars accepted');
r = await call('POST', '/auth/register', { body: { email: 'new@example.com', nickname: 'newuser', password: 'short' } });
check(r.code === 400 && r.json.error === 'weak-password', 'register: weak password');
r = await call('POST', '/auth/register', { body: { email: 'jeddahh@gmail.com', nickname: 'newuser', password: 'Password1' } });
check(r.code === 409 && r.json.error === 'email-taken', 'register: email taken');
r = await call('POST', '/auth/register', { body: { email: 'new@example.com', nickname: 'sara', password: 'Password1' } });
check(r.code === 409 && r.json.error === 'nickname-taken', 'register: nickname taken (forwarded from the core)');
r = await call('POST', '/auth/register', { body: { email: ' New@Example.com ', nickname: 'newuser', password: 'Password1' } });
check(r.code === 200 && r.json.token && r.json.id && r.json.email === 'new@example.com' && r.json.verified === false && r.json.codeSent === false && typeof r.json.recoveryPhrase === 'string', 'register: account created, email linked, phrase returned, no code while mail is off', JSON.stringify(r.json));
const newId = r.json.id;
const stored = (await pool.query('SELECT phrase_enc, source FROM account_recovery WHERE user_id=$1', [newId])).rows[0];
check(stored && stored.source === 'register' && stored.phrase_enc.startsWith('v1.') && !stored.phrase_enc.includes('عبارة'), 'phrase stored encrypted (not plaintext)');
r = await call('POST', '/auth/login', { body: { handle: 'new@example.com', password: 'Password1' } });
check(r.code === 200 && r.json.id === newId, 'new account logs in with its email');
r = await call('POST', '/auth/forgot', { body: { email: 'new@example.com' } });
check(r.code === 503 && r.json.error === 'mail-not-configured', 'forgot refused while mail is off');
// ---- تفعيل البريد من لوحة الإدارة
r = await call('PUT', '/adminapi/mail', { ...ADMIN, body: { provider: 'smtp', host: '127.0.0.1', port: smtp.port, user: 'mailer', pass: 'secret', from: 'no-reply@naslife.app' } });
check(r.code === 200 && r.json.configured === true, 'admin enables SMTP');
r = await call('POST', '/auth/register', { body: { email: 'second@example.com', nickname: 'second', password: 'Password2' } });
check(r.code === 202 && r.json.pending === true && !r.json.token && r.json.codeSent === true && r.json.recoverySent === true && smtp.messages.length === 1 && smtp.messages[0].to[0] === 'second@example.com', 'register with mail on: welcome mail sent, no session until the email is verified (gate)', JSON.stringify(r.json).slice(0, 200));
check(![...sessions.values()].includes('second'), 'the core session issued at registration was revoked');
const secondReg = r; // يُستعاد بعد فحوص البوابة لأن ما يلي يقرأ r.json.id ورسالة الترحيب الأولى
// ---- بوابة التأكيد: الدخول مرفوض قبل الرمز، ثم /auth/verify بلا جلسة، ثم الدخول يعمل
r = await call('POST', '/auth/login', { body: { handle: 'second@example.com', password: 'wrong' } });
check(r.code === 401 && r.json.error === 'bad-credentials', 'gate: wrong password is still 401 (no code resend for guessers)');
r = await call('POST', '/auth/login', { body: { handle: 'second', password: 'Password2' } });
check(r.code === 403 && r.json.error === 'email-unverified' && r.json.email === 'second@example.com' && r.json.codeSent === false && r.json.retryIn > 0 && !r.json.token && ![...sessions.values()].includes('second'), 'gate: right password before verification -> 403 email-unverified, no session, no duplicate code within a minute', JSON.stringify(r.json));
r = await call('POST', '/auth/resend', { body: { email: 'second@example.com' } });
check(r.code === 429 && r.json.error === 'too-soon' && r.json.retryIn > 0, 'gate: resend within a minute -> too-soon');
r = await call('POST', '/auth/resend', { body: { email: 'nobody@example.com' } });
check(r.code === 200 && r.json.ok === true && smtp.messages.length === 1, 'gate: resend for an unknown email answers ok without sending (no enumeration)');
r = await call('POST', '/auth/verify', { body: { email: 'second@example.com', code: '000000' } });
check(r.code === 400 && r.json.error === 'bad-code' && r.json.attemptsLeft === 4, 'gate: wrong code counts an attempt');
r = await call('POST', '/auth/verify', { body: { email: 'nobody@example.com', code: '123456' } });
check(r.code === 400 && r.json.error === 'bad-code', 'gate: unknown email behaves like a wrong code');
r = await call('POST', '/auth/verify', { body: { email: 'Second@Example.com', code: codeOf(0) } });
check(r.code === 200 && r.json.verified === true && !r.json.token, 'gate: right code verifies the email (any case) and issues no session by itself');
r = await call('POST', '/auth/login', { body: { handle: 'second@example.com', password: 'Password2' } });
check(r.code === 200 && r.json.token?.startsWith('tok-second'), 'gate: login works after verification');
r = await call('POST', '/auth/verify', { body: { email: 'second@example.com', code: '111111' } });
check(r.code === 200 && r.json.verified === true, 'gate: verify on an already verified email is a no-op ok');
// المفتاح مطفأ من الإعدادات: التسجيل يعيد الجلسة فوراً كما كان
globalThis.naslifeSettings = { requireEmailVerification: false };
r = await call('POST', '/auth/register', { body: { email: 'third@example.com', nickname: 'third', password: 'Password3' } });
check(r.code === 200 && r.json.token?.startsWith('tok-third') && r.json.codeSent === true, 'gate off (admin setting): register returns the session as before');
r = await call('POST', '/auth/login', { body: { handle: 'third', password: 'Password3' } });
check(r.code === 200 && r.json.token, 'gate off: unverified account logs in');
delete globalThis.naslifeSettings;
r = await call('POST', '/auth/login', { body: { handle: 'third', password: 'Password3' } });
check(r.code === 403 && r.json.error === 'email-unverified' && r.json.codeSent === false, 'gate on again: the same account is asked to verify (code sent a moment ago, not resent)');
r = await call('GET', '/auth/alias/status');
check(r.json.requireVerification === true, 'status reports requireVerification');
// نعود إلى حساب second: التحقق بجلسة ماي سبيس ما زال يعمل للحسابات القائمة
r = await call('POST', '/auth/register', { body: { email: 'second2@example.com', nickname: 'second2', password: 'Password2' } });
const secondGateId = r.json.id;
r = await call('POST', '/auth/login', { body: { handle: 'second', password: 'Password2' } });
check(r.code === 200 && r.json.token, 'verified account keeps logging in');
r = await call('GET', '/me/login-email', { user: secondGateId });
check(r.code === 200 && r.json.verified === false && r.json.required === true, 'login-email info exposes required=true for the app bootstrap gate', JSON.stringify(r.json));
r = await call('POST', '/me/login-email/verify', { user: secondGateId, body: { code: codeOf(smtp.messages.length - 1) } });
check(r.code === 200 && r.json.verified === true, 'session-based verify (MySpace / bootstrap gate) still works');
r = await call('POST', '/auth/register', { body: { email: 'second3@example.com', nickname: 'second3', password: 'Password2' } });
check(r.code === 202 && r.json.recoveryPhrase === undefined && r.json.hasRecovery === undefined && r.json.token === undefined, 'register keeps returning 202 while the gate is on, without the recovery phrase (it is a core credential)');
const third3Id = r.json.id;
// جلسة قائمة لحساب غير مؤكد لا تحذف بريدها هرباً من البوابة
r = await call('DELETE', '/me/login-email', { user: third3Id });
check(r.code === 403 && r.json.error === 'email-unverified', 'gate: an unverified session cannot delete its email to escape the gate');
// بريد خاطئ عند التسجيل: تغييره بكلمة السر
r = await call('POST', '/auth/change-email', { body: { handle: 'second3', password: 'wrong', email: 'fixed3@example.com' } });
check(r.code === 401, 'change-email: wrong password refused');
r = await call('POST', '/auth/change-email', { body: { handle: 'second3', password: 'Password2', email: 'jeddahh@gmail.com' } });
check(r.code === 409 && r.json.error === 'email-taken', 'change-email: cannot take another account email');
r = await call('POST', '/auth/change-email', { body: { handle: 'second3', password: 'Password2', email: 'Fixed3@Example.com' } });
check(r.code === 202 && r.json.pending === true && r.json.email === 'fixed3@example.com' && r.json.codeSent === true && !r.json.token && ![...sessions.values()].includes('second3'), 'change-email: unverified email replaced, code sent, no session', JSON.stringify(r.json));
r = await call('POST', '/auth/login', { body: { handle: 'second3@example.com', password: 'Password2' } });
check(r.code === 401, 'change-email: the old email no longer logs in');
r = await call('POST', '/auth/verify', { body: { email: 'fixed3@example.com', code: codeOf(smtp.messages.length - 1) } });
check(r.code === 200 && r.json.verified === true, 'change-email: the new email verifies with its code');
r = await call('POST', '/auth/change-email', { body: { handle: 'second3', password: 'Password2', email: 'other@example.com' } });
check(r.code === 409 && r.json.error === 'already-verified', 'change-email: a verified email is not changed from here');
r = await call('POST', '/auth/login', { body: { handle: 'fixed3@example.com', password: 'Password2' } });
check(r.code === 200 && r.json.token, 'change-email: login with the new email works');
// خمس محاولات ثم قفل حتى رمز جديد
r = await call('POST', '/auth/register', { body: { email: 'lock@example.com', nickname: 'locker', password: 'Password2' } });
for (let i = 0; i < 5; i++) r = await call('POST', '/auth/verify', { body: { email: 'lock@example.com', code: '000000' } });
check(r.code === 400 && r.json.attemptsLeft === 0, 'fifth wrong code leaves 0 attempts', JSON.stringify(r.json));
r = await call('POST', '/auth/verify', { body: { email: 'lock@example.com', code: codeOf(smtp.messages.length - 1) } });
check(r.code === 429 && r.json.error === 'too-many-attempts', 'even the right code is refused after five attempts until a new code is sent');
smtp.messages.length = 1; // نُبقي رسالة الترحيب الأولى فقط لفحوص الرسالة أدناه
r = secondReg;
{ const secondId = r.json.id; const txt = plainTextOf(smtp.messages[0].raw); const raw = smtp.messages[0].raw;
  check(txt.includes('أهلاً بك في ناس لايف، second') && txt.includes(secondId) && txt.includes('second@example.com') && txt.includes('عبارة جديدة رقم') && /\b\d{6}\b/.test(txt), 'welcome mail carries the code, account data and the recovery phrase', txt.slice(0, 120).replace(/\n/g, ' | '));
  const htmlPart = Buffer.from((raw.split(/Content-Type: text\/html[^\r\n]*\r?\nContent-Transfer-Encoding: base64\r?\n\r?\n/)[1] || '').split(/\r?\n--/)[0].replace(/\s+/g, ''), 'base64').toString('utf8');
  check(/Subject: =\?UTF-8\?B\?/.test(raw) && htmlPart.includes('Icon-192.png') && htmlPart.includes('018828'.length === 6 ? 'رمز التأكيد' : '') && htmlPart.includes('عبارة الاسترداد'), 'welcome mail has an encoded subject and an HTML part with the brand header, code and phrase'); }
const secondId = r.json.id;
r = await call('POST', '/me/login-email/verify', { user: secondId, body: { code: codeOf(0) } });
check(r.code === 200 && r.json.verified === true, 'new account verifies its email with the code');
// ---- نسيت كلمة السر
r = await call('POST', '/auth/forgot', { body: { email: 'nobody@example.com' } });
check(r.code === 200 && r.json.ok === true && smtp.messages.length === 1, 'forgot for unknown email: generic ok, no mail');
r = await call('POST', '/auth/forgot', { body: { email: 'new@example.com' } });
check(r.code === 200 && smtp.messages.length === 2 && smtp.messages[1].to[0] === 'new@example.com' && plainTextOf(smtp.messages[1].raw).includes('newuser'), 'forgot sends a reset code naming the account');
const reset1 = codeOf(1);
r = await call('POST', '/auth/forgot', { body: { email: 'new@example.com' } });
check(r.code === 429 && r.json.error === 'too-soon', 'forgot again within 60s refused');
r = await call('POST', '/auth/reset', { body: { email: 'new@example.com', code: '000000', password: 'NewPass123' } });
check(r.code === 400 && r.json.error === 'bad-code' && r.json.attemptsLeft === 4, 'reset with wrong code counts an attempt');
r = await call('POST', '/auth/reset', { body: { email: 'new@example.com', code: reset1, password: 'short' } });
check(r.code === 400 && r.json.error === 'weak-password', 'reset with weak password refused before consuming the code');
r = await call('POST', '/auth/reset', { body: { email: 'new@example.com', code: reset1, password: 'NewPass123' } });
check(r.code === 200 && r.json.token && r.json.id === newId && r.json.recoveryPhrase === undefined && r.json.verified === true, 'reset with the right code: new session, phrase hidden, email marked verified', JSON.stringify(r.json));
check(accounts.newuser.password === 'NewPass123', 'core password actually changed');
const stored2 = (await pool.query('SELECT phrase_enc, source FROM account_recovery WHERE user_id=$1', [newId])).rows[0];
check(stored2.source === 'reset' && stored2.phrase_enc !== stored.phrase_enc, 'rotated phrase stored after reset');
r = await call('POST', '/auth/login', { body: { handle: 'new@example.com', password: 'Password1' } });
check(r.code === 401, 'old password no longer works');
r = await call('POST', '/auth/login', { body: { handle: 'new@example.com', password: 'NewPass123' } });
check(r.code === 200, 'new password works');
const tokNew = r.json.token;
r = await call('POST', '/auth/reset', { body: { email: 'new@example.com', code: reset1, password: 'NewPass123' } });
check(r.code === 400 && r.json.error === 'bad-code', 'used code cannot be replayed');
// ---- تغيير كلمة السر
r = await call('POST', '/auth/change-password', { token: tokNew, body: { current: 'wrong', password: 'Another123' } });
check(r.code === 403 && r.json.error === 'bad-password', 'change-password: wrong current');
r = await call('POST', '/auth/change-password', { token: tokNew, body: { current: 'NewPass123', password: 'Another123' } });
check(r.code === 200 && r.json.ok === true && r.json.token && r.json.token !== tokNew, 'change-password: ok with a fresh session token', JSON.stringify(r.json));
r = await call('POST', '/auth/login', { body: { handle: 'newuser', password: 'Another123' } });
check(r.code === 200, 'login with the changed password (nickname)');
r = await call('POST', '/auth/change-password', { body: { current: 'x', password: 'Another123' } });
check(r.code === 401 && r.json.error === 'auth', 'change-password needs auth');
// ---- حساب قديم بلا عبارة محفوظة: نسيت كلمة السر يرسل شرحاً، والتفعيل من ماي سبيس يحل الأمر
r = await call('GET', '/me/recovery', ADMIN);
check(r.code === 200 && r.json.enabled === false && r.json.email === 'jeddahh@gmail.com' && r.json.mailConfigured === true, 'legacy account: recovery not enabled yet', JSON.stringify(r.json));
r = await call('POST', '/auth/forgot', { body: { email: 'jeddahh@gmail.com' } });
check(r.code === 200 && smtp.messages.length === 3 && plainTextOf(smtp.messages[2].raw).includes('غير مفعّلة') && !/\b\d{6}\b/.test(plainTextOf(smtp.messages[2].raw)), 'forgot for legacy account mails an explanation instead of a code');
r = await call('PUT', '/me/recovery', { ...ADMIN, body: { phrase: 'wrong words', password: 'TestPass#2026' } });
check(r.code === 400 && r.json.error === 'bad-phrase', 'enable recovery: wrong phrase');
r = await call('PUT', '/me/recovery', { ...ADMIN, body: { phrase: 'حلوى موج فندق شكل كمان بطاطس', password: 'nope' } });
check(r.code === 403 && r.json.error === 'bad-password', 'enable recovery: wrong password');
r = await call('PUT', '/me/recovery', { ...ADMIN, body: { phrase: ' حلوى  موج فندق شكل كمان بطاطس ', password: 'TestPass#2026' } });
check(r.code === 200 && r.json.enabled === true && r.json.token, 'enable recovery with the phrase (whitespace normalized) returns a new session');
check(accounts.jeddahh.password === 'TestPass#2026' && accounts.jeddahh.phrase !== 'حلوى موج فندق شكل كمان بطاطس', 'password unchanged, core phrase rotated and stored');
r = await call('GET', '/me/recovery', ADMIN);
check(r.json.enabled === true, 'recovery now enabled');
await pool.query("UPDATE login_aliases SET reset_sent_at = now() - interval '2 minutes' WHERE alias='jeddahh@gmail.com'");
r = await call('POST', '/auth/forgot', { body: { email: 'jeddahh@gmail.com' } });
check(r.code === 200 && smtp.messages.length === 4 && !!codeOf(3), 'legacy account now receives a real reset code');
r = await call('POST', '/auth/reset', { body: { email: 'jeddahh@gmail.com', code: codeOf(3), password: 'Founder2026!' } });
check(r.code === 200 && r.json.id === 'SA9954961' && accounts.jeddahh.password === 'Founder2026!', 'legacy account resets its password by email');
// ---- انتهاء الصلاحية والمحاولات
await pool.query("UPDATE login_aliases SET reset_hash='x', reset_exp = now() - interval '1 minute' WHERE alias='new@example.com'");
r = await call('POST', '/auth/reset', { body: { email: 'new@example.com', code: '123456', password: 'Whatever123' } });
check(r.code === 410 && r.json.error === 'code-expired', 'expired reset code reported');
await pool.query("UPDATE login_aliases SET reset_hash='x', reset_exp = now() + interval '10 minute', reset_attempts=5 WHERE alias='new@example.com'");
r = await call('POST', '/auth/reset', { body: { email: 'new@example.com', code: '123456', password: 'Whatever123' } });
check(r.code === 429 && r.json.error === 'too-many-attempts', 'exhausted attempts refused');
// ---- بريد الدخول (كما قبل)
r = await call('GET', '/me/login-email', ADMIN);
check(r.code === 200 && r.json.email === 'jeddahh@gmail.com' && r.json.verified === true, 'my login email');
r = await call('PUT', '/me/login-email', { ...SARA, body: { email: 'jeddahh@gmail.com' } });
check(r.code === 409 && r.json.error === 'email-taken', 'cannot take another user\'s email');
r = await call('PUT', '/me/login-email', { ...SARA, body: { email: 'sara@example.com' } });
check(r.code === 200 && r.json.email === 'sara@example.com' && r.json.codeSent === true, 'set my login email sends a code');
r = await call('POST', '/me/login-email/send-code', { ...SARA, body: {} });
check(r.code === 429 && r.json.error === 'too-soon', 'resend within 60s refused');
r = await call('POST', '/me/login-email/verify', { ...SARA, body: { code: codeOf(smtp.messages.length - 1) } });
check(r.code === 200 && r.json.verified === true, 'verify my email');
r = await call('DELETE', '/me/login-email', SARA);
check(r.code === 200 && (await call('POST', '/auth/login', { body: { handle: 'sara@example.com', password: 'secret' } })).code === 401, 'delete my login email');
r = await call('GET', '/auth/alias/status');
check(r.json.recoverable === 7, 'status counts recoverable accounts (3 original + third, second2, second3, locker from the gate checks)', JSON.stringify(r.json));
console.log(fails ? `\n${fails} FAILED` : '\nALL AUTH ALIAS TESTS PASSED');
await app.close(); await smtp.close(); await pool.end(); process.exit(fails ? 1 : 0);
